var CRM_PROGRAMS_=["AI Engineering Training Internship", "Forward Deployment Engineering", "Space Technology and Satellite Systems", "Machine Learning", "Full-Stack Development", "Forward Deployment Engineering for Leaders"];
/** Prepared only. Install this in a BOUND Apps Script project for each private workbook.
 * The intake project may include it too for immediate reconciliation after save.
 * No triggers, messages, sharing or retention deletion are enabled by this file.
 */
var CRM_COLUMNS_=['Reference','Received UTC','Name','Email','Phone','Programs / idea','Mode','Status','Assigned owner','Priority','Last contact','Next action','Next follow-up','Internal notes','Decision reason','Active engagement','Advisory stage','Next milestone','Target date','Updated UTC','Possible repeat'];
var CRM_KEYS_=['reference','received','name','email','phone','programs','mode','status','owner','priority','lastContact','nextAction','followUp','notes','reason','active','stage','milestone','target','updated','repeat'];
var CRM_CONTEXT_KIND_='';
function crmKind_(){if(CRM_CONTEXT_KIND_)return CRM_CONTEXT_KIND_;return PropertiesService.getScriptProperties().getProperty('CRM_KIND')==='venture'?'venture':'program';}
function crmBook_(kind){var p=PropertiesService.getScriptProperties(),id=p.getProperty(kind==='venture'?'VENTURE_SPREADSHEET_ID':'SPREADSHEET_ID');if(!id)throw Error('Configure the private spreadsheet ID first');return SpreadsheetApp.openById(id);}
function onOpen(){SpreadsheetApp.getUi().createMenu('Academy CRM').addItem('Refresh CRM','refreshCrm').addItem('Review retention (dry run)','reviewRetention').addToUi();}
function crmSheet_(book,name){return book.getSheetByName(name)||book.insertSheet(name);}
function crmWrite_(sheet,headers,rows){sheet.clearContents();sheet.getRange(1,1,1,headers.length).setValues([headers]).setBackground('#102c56').setFontColor('#ffffff').setFontWeight('bold');if(rows.length)sheet.getRange(2,1,rows.length,headers.length).setNumberFormat('@').setValues(rows.map(r=>r.map(v=>typeof v==='boolean'?v:safeCell_(v==null?'':v))));sheet.setFrozenRows(1);sheet.setRowHeight(1,36);sheet.setTabColor('#205c99');}
function crmSource_(book,kind){var p=PropertiesService.getScriptProperties(),key=kind==='venture'?'VENTURE_SOURCE_SHEET':'SOURCE_SHEET',sheet=book.getSheetByName(p.getProperty(key)||'Source Responses')||book.getSheetByName('Enquiries');if(!sheet)throw Error('Source responses missing. Initialise intake first.');return sheet;}
function sourceRecords_(sheet,kind){var rows=sheet.getDataRange().getValues();return rows.slice(1).filter(r=>r[1]).map(r=>kind==='venture'?{received:r[0],reference:r[1],name:r[2],email:r[3],phone:r[4],programs:[r[6]],mode:r[16]}:{received:r[0],reference:r[1],name:r[3],email:r[4],phone:r[5],programs:String(r[2]||'').split(',').map(s=>s.trim()),mode:r[14]});}
function pipelineRecords_(sheet){if(sheet.getLastRow()<2)return [];return sheet.getRange(2,1,sheet.getLastRow()-1,CRM_KEYS_.length).getValues().filter(row=>String(row[0]||'').trim()).map(row=>{var r={};CRM_KEYS_.forEach((k,i)=>r[k]=row[i]);r.programs=String(r.programs).split(' | ').filter(Boolean);r.active=r.active===true||r.active==='TRUE';r.repeat=r.repeat===true||r.repeat==='TRUE';return r;});}
function pipelineRow_(r){return CRM_KEYS_.map(k=>k==='programs'?(r.programs||[]).join(' | '):r[k]==null?'':r[k]);}
function reconcileCrm_(kind){var book=crmBook_(kind),source=crmSource_(book,kind),sheet=crmSheet_(book,'Pipeline'),old=pipelineRecords_(sheet),result=CRMCore.reconcile(sourceRecords_(source,kind),old,kind);if(!sheet.getLastRow())crmWrite_(sheet,CRM_COLUMNS_,[]);var known=new Set(old.map(r=>r.reference));result.records.forEach(r=>{if(!known.has(r.reference)){sheet.getRange(sheet.getLastRow()+1,1,1,CRM_COLUMNS_.length).setNumberFormat('@').setValues([pipelineRow_(r).map(v=>typeof v==='boolean'?v:safeCell_(v))]);[11,13,19].forEach(c=>sheet.getRange(sheet.getLastRow(),c).setNumberFormat(c===11?'yyyy-mm-dd hh:mm':'yyyy-mm-dd'));known.add(r.reference)}});var p=PropertiesService.getScriptProperties();p.setProperty('CRM_ERROR_'+kind,result.errors.join('; ')||'');if(old.length){var current=sheet.getRange(2,1,Math.max(sheet.getLastRow()-1,1),1).getValues();var repeats=new Map(result.records.map(r=>[r.reference,r.repeat]));sheet.getRange(2,21,current.length,1).setValues(current.map(r=>[repeats.get(r[0])||false]));}return result;}
function setupCrm(){var existing=crmBook_(crmKind_());if(!existing.getSheetByName('Settings')&&existing.getSheetByName('Pipeline')&&existing.getSheetByName('Activity')){reconcileCrm_(crmKind_());return;}var kind=crmKind_(),book=crmBook_(kind),source=crmSource_(book,kind);PropertiesService.getScriptProperties().setProperty(kind==='venture'?'VENTURE_SOURCE_SHEET':'SOURCE_SHEET',source.getName());if(source.getName()!=='Source Responses'){var mirror=crmSheet_(book,'Source Responses'),v=source.getDataRange().getValues();crmWrite_(mirror,v[0],v.slice(1));}
 ['Dashboard','Pipeline','Follow-ups','Activity','Settings','Read Me','Retention Review','Program Interests'].forEach(n=>crmSheet_(book,n));
 var settings=book.getSheetByName('Settings');if(!settings.getLastRow())crmWrite_(settings,['Setting','Value'],[['Mode','Live'],['Received from (IST date)',''],['Received to (IST date)',''],['Owner','All'],['Status','All'],['Program','All'],['Advisory stage','All']]);
 var activity=book.getSheetByName('Activity');if(!activity.getLastRow())crmWrite_(activity,['Reference','Changed UTC','Field','Previous value','New value','Editor'],[]);
 crmWrite_(book.getSheetByName('Read Me'),['Academy private CRM','How to use'],[['1. Dashboard','Use Settings filters then Academy CRM → Refresh CRM. Native charts show the selected received-date cohort.'],['2. Pipeline','Edit management columns H:S only. Sort the full table or use a filter view; never sort a single column.'],['3. Follow-ups','Review actions; no automatic email is sent.'],['4. Source','Original submissions are preserved. References identify records, never row numbers.'],['5. Privacy','File sharing controls access. Protection prevents accidental edits, not disclosure to authorised viewers.'],['6. Retention','Review is dry-run. Client must approve export/version-history handling before enabling deletion.'],['7. Activity','Install an on-edit trigger after approval. Identity may be unavailable; this is not a tamper-proof audit trail.'],['8. Accepted ideas','Accepted means suitable for further discussion, not a paid engagement or delivery commitment.'],['9. Time','Submission timestamps are UTC. Cohort dates and operational dates use Asia/Kolkata.'],['10. Filters','Data → Filter views lets each staff member filter Pipeline without changing colleagues’ views.'],['11. Samples','Live excludes Sample/Prototype records. Choose Sample explicitly for review.']]);
 book.setSpreadsheetTimeZone('Asia/Kolkata');reconcileCrm_(kind);var pipe=book.getSheetByName('Pipeline'),n=Math.max(pipe.getMaxRows()-1,1);
 function dropdown(col,values){pipe.getRange(2,col,n,1).setDataValidation(SpreadsheetApp.newDataValidation().requireValueInList(values,true).setAllowInvalid(false).build());}
 dropdown(8,CRMCore.statuses[kind]);dropdown(10,['Low','Normal','High']);dropdown(17,CRMCore.stages);pipe.getRange(2,16,n,1).setDataValidation(SpreadsheetApp.newDataValidation().requireCheckbox().build());[11,13,19].forEach(c=>pipe.getRange(2,c,n,1).setDataValidation(SpreadsheetApp.newDataValidation().requireDate().setAllowInvalid(false).build()).setNumberFormat(c===11?'yyyy-mm-dd hh:mm':'yyyy-mm-dd'));
 if(!pipe.getFilter())pipe.getRange(1,1,pipe.getMaxRows(),CRM_COLUMNS_.length).createFilter();pipe.setFrozenColumns(3);pipe.setColumnWidths(1,CRM_COLUMNS_.length,150);pipe.setColumnWidths(12,3,240);
 var rules=[SpreadsheetApp.newConditionalFormatRule().whenFormulaSatisfied('=AND($M2<>"",$M2<TODAY(),NOT(OR($H2="Joined",$H2="Closed",$H2="Not interested",$H2="Completed",$H2="Declined")))').setBackground('#ffebe7').setRanges([pipe.getRange(2,1,n,21)]).build(),SpreadsheetApp.newConditionalFormatRule().whenCellEmpty().setBackground('#fff3ce').setRanges([pipe.getRange(2,9,n,1),pipe.getRange(2,12,n,1)]).build()];pipe.setConditionalFormatRules(rules);
 settings.getRange('B2').setDataValidation(SpreadsheetApp.newDataValidation().requireValueInList(['Live','Sample'],true).setAllowInvalid(false).build());settings.getRange('B3:B4').setDataValidation(SpreadsheetApp.newDataValidation().requireDate().setAllowInvalid(false).build()).setNumberFormat('yyyy-mm-dd');
 refreshCrm();protectCrm_(book);try{onOpen();}catch(e){console.log('Open the workbook to use its bound menu after setup.');}
}
function protectCrm_(book){['Enquiries','Source Responses','Dashboard','Follow-ups','Activity','Program Interests','Retention Review'].forEach(name=>{var s=book.getSheetByName(name);if(!s)return;if(!s.getProtections(SpreadsheetApp.ProtectionType.SHEET).length){var p=s.protect().setDescription('Academy generated/source data');p.removeEditors(p.getEditors());if(p.canDomainEdit())p.setDomainEdit(false);}});var pipe=book.getSheetByName('Pipeline');if(!pipe.getProtections(SpreadsheetApp.ProtectionType.SHEET).length){var p=pipe.protect().setDescription('Edit management fields only');p.setUnprotectedRanges([pipe.getRange(2,8,pipe.getMaxRows()-1,12)]);p.removeEditors(p.getEditors());if(p.canDomainEdit())p.setDomainEdit(false);}}
function filters_(book){var v=book.getSheetByName('Settings').getRange('B2:B8').getValues().flat();return {mode:v[0]||'Live',from:v[1]?CRMCore.date(v[1]):'',to:v[2]?CRMCore.date(v[2]):'',owner:v[3],status:v[4],program:v[5],stage:v[6]};}
function refreshCrm(){if(!crmBook_(crmKind_()).getSheetByName('Settings'))return reconcileCrm_(crmKind_());var lock=LockService.getScriptLock();if(!lock.tryLock(5000))throw Error('CRM busy; retry');try{var kind=crmKind_(),book=crmBook_(kind),result=reconcileCrm_(kind),records=result.records,now=new Date().toISOString(),d=CRMCore.dashboard(records,filters_(book),kind,now),sheet=book.getSheetByName('Dashboard');crmDashboardView_(book,kind,d,filters_(book),now,result.errors.length>0);
 crmWrite_(book.getSheetByName('Follow-ups'),['Reference','Name','Owner','Status','Next action','Follow-up','Attention'],CRMCore.followups(d.rows,now).map(r=>[r.reference,r.name,r.owner,r.status,r.nextAction,r.followUp,r.flags]));crmWrite_(book.getSheetByName('Program Interests'),['Reference','Program','Mode'],records.flatMap(r=>(r.programs||[]).map(p=>[r.reference,p,r.mode])));
 var original=crmSource_(book,kind);if(original.getName()!=='Source Responses'){var values=original.getDataRange().getValues();crmWrite_(book.getSheetByName('Source Responses'),values[0],values.slice(1));}
 var settings=book.getSheetByName('Settings');[[5,['All',...new Set(records.map(r=>r.owner).filter(Boolean))]],[6,['All',...CRMCore.statuses[kind]]],[7,['All',...new Set([...(kind==='program'?CRM_PROGRAMS_:[]),...records.flatMap(r=>r.programs||[])])]],[8,['All',...CRMCore.stages]]].forEach(([row,values])=>settings.getRange(row,2).setDataValidation(SpreadsheetApp.newDataValidation().requireValueInList(values,true).setAllowInvalid(false).build()));
 }finally{lock.releaseLock();}}
function crmOnEdit(e){if(e&&e.source){CRM_CONTEXT_KIND_=e.source.getId()===PropertiesService.getScriptProperties().getProperty('VENTURE_SPREADSHEET_ID')?'venture':'program';if(e.range.getSheet().getName()==='Settings'){e.source.getSheetByName('Dashboard').getRange('A3').setValue('Filters changed — use Academy CRM → Refresh CRM');return;}}if(!e||e.range.getSheet().getName()!=='Pipeline')return;if(e.range.getRow()<2||e.range.getColumn()<8||e.range.getLastColumn()>19)return;var book=e.source,kind=crmKind_(),sheet=e.range.getSheet(),activity=book.getSheetByName('Activity'),editor='Unavailable';try{if(e.user)editor=e.user.getEmail()||'Unavailable';}catch(ignore){}var rows=e.range.getValues();rows.forEach((row,ri)=>{var at=e.range.getRow()+ri,ref=sheet.getRange(at,1).getValue();row.forEach((value,ci)=>activity.appendRow([ref,new Date().toISOString(),CRM_KEYS_[e.range.getColumn()+ci-1],rows.length===1&&row.length===1?safeCell_(e.oldValue==null?'':e.oldValue):'Unavailable (bulk edit)',safeCell_(value),editor||'Unavailable']));sheet.getRange(at,20).setValue(new Date().toISOString());});PropertiesService.getScriptProperties().setProperty('CRM_DIRTY_'+kind,'true');}
function reviewRetention(){var kind=crmKind_(),book=crmBook_(kind),report=CRMCore.retention(pipelineRecords_(book.getSheetByName('Pipeline')),new Date().toISOString());crmWrite_(crmSheet_(book,'Retention Review'),['Reference','Eligible (dry run)','Reason','Retention basis UTC','Elapsed days'],report.map(r=>[r.reference,r.eligible,r.reason,r.basis,r.days]));}
function executeApprovedRetention_(){var p=PropertiesService.getScriptProperties();if(p.getProperty('RETENTION_ENABLED')!=='true'||p.getProperty('EXPORT_HISTORY_HANDLING_APPROVED')!=='true')throw Error('Retention remains dry-run pending client approval, export and version-history handling');var lock=LockService.getScriptLock();if(!lock.tryLock(5000))throw Error('CRM busy');try{var kind=crmKind_(),book=crmBook_(kind),refs=new Set(CRMCore.retention(pipelineRecords_(book.getSheetByName('Pipeline')),new Date().toISOString()).filter(r=>r.eligible).map(r=>r.reference));[['Enquiries',2],['Source Responses',2],['Pipeline',1],['Activity',1],['Program Interests',1],['Follow-ups',1],['Retention Review',1]].forEach(([name,col])=>{var s=book.getSheetByName(name);if(!s)return;var rows=s.getDataRange().getValues();for(var i=rows.length-1;i>=1;i--)if(refs.has(rows[i][col-1]))s.deleteRow(i+1);});}finally{lock.releaseLock();}refreshCrm();}
