/* Pure reporting rules shared by Apps Script and local verification. No network or storage. */
var CRMCore=(function(){
 const statuses={program:['New','Contacted','Qualified','Joined','On hold','Not interested','Closed'],venture:['New','Under review','Clarification requested','Discussion scheduled','Accepted','Active engagement','Completed','On hold','Declined']};
 const stages=['Idea & opportunity','Customer validation','Business model','MVP planning','Pilot & launch','Measure & learn','Scale readiness'];
 const closed=['Joined','Not interested','Closed','Completed','Declined'];
 const day=86400000;
 function iso(value){if(!value)return '';const d=new Date(value);return Number.isNaN(+d)?'':d.toISOString();}
 function date(value){const v=iso(value);return v?new Date(+new Date(v)+19800000).toISOString().slice(0,10):'';}
 function text(v){return String(v==null?'':v).trim();}
 function normalize(r,kind){const x={...r};x.reference=text(r.reference);if(!x.reference)throw Error('Missing reference');x.received=iso(r.received);if(!x.received)throw Error('Invalid received timestamp: '+x.reference);x.kind=kind;x.status=statuses[kind].includes(r.status)?r.status:'New';x.email=text(r.email).replace(/^'/,'').toLowerCase();x.phone=text(r.phone).replace(/\D/g,'');x.mode=/^(sample|prototype|test)$/i.test(text(r.mode))?'Sample':'Live';x.programs=Array.from(new Set((Array.isArray(r.programs)?r.programs:text(r.programs).split(',')).map(text).filter(Boolean)));x.active=r.active===true||r.active==='TRUE';return x;}
 function reconcile(source,pipeline,kind){const records=pipeline.map(r=>({...r})),seen=new Map(),errors=[];records.forEach(r=>{if(seen.has(r.reference))errors.push('Duplicate pipeline reference: '+r.reference);seen.set(r.reference,r)});const sourceSeen=new Set();source.forEach(raw=>{try{const r=normalize(raw,kind);if(sourceSeen.has(r.reference)){errors.push('Duplicate source reference: '+r.reference);return}sourceSeen.add(r.reference);if(!seen.has(r.reference)){const n={...r,status:'New',owner:'',priority:'Normal',lastContact:'',nextAction:'',followUp:'',notes:'',reason:'',active:false,stage:kind==='venture'?stages[0]:'',milestone:'',target:'',updated:''};records.push(n);seen.set(r.reference,n)}}catch(e){errors.push(e.message)}});const emails=new Map(),phones=new Map();records.forEach(r=>{if(r.email)emails.set(r.email,(emails.get(r.email)||0)+1);if(r.phone)phones.set(r.phone,(phones.get(r.phone)||0)+1)});records.forEach(r=>r.repeat=Boolean((r.email&&emails.get(r.email)>1)||(r.phone&&phones.get(r.phone)>1)));return {records,errors};}
 function select(records,f){f=f||{};const seen=new Set();return records.filter(r=>{if(seen.has(r.reference))return false;seen.add(r.reference);const d=date(r.received);return r.mode===(f.mode||'Live')&&(!f.from||d>=f.from)&&(!f.to||d<=f.to)&&(!f.owner||f.owner==='All'||r.owner===f.owner)&&(!f.status||f.status==='All'||r.status===f.status)&&(!f.program||f.program==='All'||(r.programs||[]).includes(f.program))&&(!f.stage||f.stage==='All'||r.stage===f.stage)});}
 function due(r,now){if(closed.includes(r.status)||!r.followUp)return '';const d=/^\d{4}-\d{2}-\d{2}$/.test(r.followUp)?r.followUp:date(r.followUp);if(!d)return '';return d<date(now)?'Overdue':d===date(now)?'Due today':'';}
 function dashboard(records,f,kind,now){now=now||new Date().toISOString();const rows=select(records,f),counts=Object.fromEntries(statuses[kind].map(s=>[s,0])),months={},ages={'0–7 days':0,'8–30 days':0,'31–60 days':0,'61+ days':0};rows.forEach(r=>{counts[r.status]=(counts[r.status]||0)+1;const m=date(r.received).slice(0,7);months[m]=(months[m]||0)+1;if(!closed.includes(r.status)){const a=Math.max(0,Math.floor((+new Date(now)-+new Date(r.received))/day));ages[a<=7?'0–7 days':a<=30?'8–30 days':a<=60?'31–60 days':'61+ days']++}});const overdue=rows.filter(r=>due(r,now)==='Overdue').length;const metrics=kind==='program'?{'Total enquiries':rows.length,'New / uncontacted':rows.filter(r=>r.status==='New'&&!r.lastContact).length,Qualified:counts.Qualified,Joined:counts.Joined,'Follow-ups due':rows.filter(r=>due(r,now)).length,'Overdue follow-ups':overdue,'Conversion %':rows.length?Math.round(counts.Joined/rows.length*1000)/10:0}:{'Total ideas':rows.length,'Awaiting review':counts.New+counts['Under review'],'Awaiting clarification':counts['Clarification requested'],Accepted:counts.Accepted,'Active engagements':rows.filter(r=>r.active||r.status==='Active engagement').length,'Overdue follow-ups':overdue};return {metrics,counts,months:Object.fromEntries(Object.entries(months).sort()),ages,rows,refreshed:iso(now)};}
 function followups(records,now){return records.filter(r=>!closed.includes(r.status)).map(r=>({...r,flags:[due(r,now),!r.owner?'Needs owner':'',!r.nextAction?'Needs next step':''].filter(Boolean).join(' · ')})).filter(r=>r.flags).sort((a,b)=>String(a.followUp||'9999').localeCompare(String(b.followUp||'9999')));}
 function retention(records,now){return records.map(r=>{const active=r.active||['Joined','Active engagement'].includes(r.status);const base=r.lastContact?iso(r.lastContact):iso(r.received);const age=base?Math.floor((+new Date(now)-+new Date(base))/day):null;return {reference:r.reference,eligible:!active&&age!==null&&age>=90,reason:active?'Active engagement — separate terms':age===null?'Invalid date — manual review':age>=90?'90-day inactive boundary reached':'Within retention period',basis:base,days:age}});}
 function removeReferences(records,refs){const set=new Set(refs);return records.filter(r=>!set.has(r.reference));}
 function edit(record,field,value,kind,now,editor){const fields=['status','owner','priority','lastContact','nextAction','followUp','notes','reason','active','stage','milestone','target'];if(!fields.includes(field))throw Error('Read-only field');if(field==='status'&&!statuses[kind].includes(value))throw Error('Invalid status');if(field==='priority'&&!['Low','Normal','High'].includes(value))throw Error('Invalid priority');if(['lastContact','followUp','target'].includes(field)&&value&&!iso(value))throw Error('Invalid date');if(field==='stage'&&value&&!stages.includes(value))throw Error('Invalid stage');const updated={...record,[field]:value,updated:iso(now)};return {record:updated,activity:{reference:record.reference,at:iso(now),field,before:text(record[field]),after:text(value),editor:editor||'Unavailable'}};}
 return {statuses,stages,iso,date,normalize,reconcile,select,due,dashboard,followups,retention,removeReferences,edit};
})();
