/** Private Google Sheets dashboard presentation. No source records or staff decisions are changed. */
function crmDashboardView_(book,kind,d,filters,now,error){
 var sheet=book.getSheetByName('Dashboard'),navy='#112b49',blue='#1768a6',teal='#087d85',gold='#a76413',red='#ac3d49';
 sheet.getCharts().forEach(c=>sheet.removeChart(c));sheet.getRange(1,1,sheet.getMaxRows(),sheet.getMaxColumns()).breakApart();sheet.clear();sheet.setHiddenGridlines(true);sheet.setColumnWidths(1,15,74);sheet.setRowHeights(1,60,23);sheet.getRange('A1:O60').setBackground('#eef2f6').setFontFamily('Arial').setFontColor(navy).setVerticalAlignment('middle');
 function bar(range,text,bg,fg,size){return sheet.getRange(range).merge().setValue(text).setBackground(bg).setFontColor(fg).setFontSize(size).setFontWeight('bold');}
 bar('A1:O2',kind==='venture'?'  VENTURE IDEAS  /  ADVISORY PIPELINE':'  PROGRAM ENQUIRIES  /  ACADEMY CRM',navy,'#ffffff',22);
 bar('A3:O3','  '+String(filters.mode).toUpperCase()+' VIEW  •  '+Utilities.formatDate(new Date(now),'Asia/Kolkata','dd MMM yyyy, HH:mm')+' IST  •  '+(error?'RECONCILIATION NEEDS REVIEW':'DATA RECONCILED'),error?red:'#214e72','#ffffff',10);
 [['A4:C4','Pipeline'],['E4:G4','Follow-ups'],['I4:K4','Settings'],['M4:O4','Read Me']].forEach(([range,name])=>{var tab=book.getSheetByName(name);bar(range,'',navy,'#ffffff',11).setFormula('=HYPERLINK("#gid='+tab.getSheetId()+'","'+name+'  ↗")').setHorizontalAlignment('center');});
 var cards=Object.entries(d.metrics);cards.push(['Needs an owner',d.rows.filter(r=>!r.owner&&!['Joined','Closed','Not interested','Completed','Declined'].includes(r.status)).length]);if(kind==='venture')cards.push(['Follow-ups due',CRMCore.followups(d.rows,now).filter(r=>CRMCore.due(r,now)).length]);
 var hues=[navy,blue,teal,blue,teal,red,gold,navy];cards.slice(0,8).forEach(([label,value],i)=>{var row=6+Math.floor(i/4)*5,col=1+(i%4)*4,bg=hues[i];sheet.getRange(row,col,4,3).setBackground(bg).setFontColor('#ffffff');sheet.getRange(row,col,1,3).merge().setValue(label.toUpperCase()).setFontSize(9).setFontWeight('bold').setHorizontalAlignment('center');sheet.getRange(row+1,col,2,3).merge().setValue(value).setFontSize(32).setFontWeight('bold').setHorizontalAlignment('center').setNumberFormat(label==='Conversion %'?'0.0"%"':'0');sheet.getRange(row+3,col,1,3).merge().setValue(label==='Conversion %'?'Joined / selected unique enquiries':label==='Needs an owner'?'Open records without an owner':'Selected received-date cohort').setFontSize(8).setHorizontalAlignment('center');});
 bar('A16:O17','  Filters: '+[filters.from||'Any start',filters.to||'Any end',filters.owner||'All owners',filters.status||'All statuses',kind==='program'?filters.program||'All programs':filters.stage||'All stages'].join('  ·  ')+'\n  Change filters in Settings, then use Academy CRM → Refresh CRM. Live excludes sample records.','#ffffff',navy,10).setWrap(true).setFontWeight('normal');
 var data=book.getSheetByName('Dashboard Data')||book.insertSheet('Dashboard Data');data.clearContents();data.setHiddenGridlines(true);var detail={};d.rows.forEach(r=>{(kind==='venture'?[r.stage||'Not assigned']:(r.programs||[])).forEach(p=>detail[p]=(detail[p]||0)+1)});
 var charts=[['Current pipeline',d.counts,Charts.ChartType.PIE,19,1],['Monthly submissions',d.months,Charts.ChartType.COLUMN,19,9],['Age of unresolved records',d.ages,Charts.ChartType.BAR,33,1],[kind==='venture'?'Advisory stages':'Program interests',detail,Charts.ChartType.BAR,33,9]];
 charts.forEach((spec,i)=>{var entries=Object.entries(spec[1]),offset=1+i*35;data.getRange(offset,1,1,2).setValues([[spec[0],'Count']]);if(!entries.length||!entries.some(e=>e[1]>0)){bar(''+(i%2?'I':'A')+(spec[3]+2)+':'+(i%2?'O':'G')+(spec[3]+9),spec[0]+'\nNo records in the selected view','#ffffff','#60748b',14).setWrap(true).setHorizontalAlignment('center');return;}data.getRange(offset+1,1,entries.length,2).setValues(entries);var builder=sheet.newChart().setChartType(spec[2]).addRange(data.getRange(offset,1,entries.length+1,2)).setNumHeaders(1).setHiddenDimensionStrategy(Charts.ChartHiddenDimensionStrategy.SHOW_BOTH).setPosition(spec[3],spec[4],0,0).setOption('width',518).setOption('height',295).setOption('title',spec[0]).setOption('titleTextStyle',{color:navy,fontSize:15,bold:true}).setOption('fontName','Arial').setOption('backgroundColor','#ffffff').setOption('colors',[blue,teal,'#e2a83c','#527dc0','#31516d','#8db3cd',red]).setOption('legend',{position:i===0?'right':'none',textStyle:{fontSize:10,color:navy}});if(i===0)builder.setOption('pieHole',0.62).setOption('pieSliceText','value');sheet.insertChart(builder.build());});data.hideSheet();
 bar('A47:O48',kind==='program'?'Program-interest counts can include a person in more than one program. Overall totals count unique enquiry references.':'Accepted means suitable for further discussion. It does not automatically create a paid engagement or delivery commitment.','#ffffff','#52667e',10).setWrap(true).setFontWeight('normal');sheet.setFrozenRows(4);sheet.setTabColor(blue);
 crmStyleTables_(book,kind);
}
function crmStyleTables_(book,kind){
 ['Pipeline','Follow-ups','Activity','Settings','Read Me','Source Responses','Program Interests'].forEach(name=>{var s=book.getSheetByName(name);if(!s)return;var cols=s.getLastColumn(),rows=Math.max(2,s.getLastRow());s.setHiddenGridlines(true);s.setTabColor(name==='Pipeline'?'#1768a6':name==='Follow-ups'?'#ac3d49':name==='Settings'?'#a76413':'#087d85');s.getRange(1,1,rows,cols).setFontFamily('Arial').setFontSize(10).setVerticalAlignment('middle');s.getRange(1,1,1,cols).setBackground('#112b49').setFontColor('#ffffff').setFontWeight('bold').setWrap(true);s.setRowHeight(1,42);s.setRowHeights(2,rows-1,32);s.setFrozenRows(1);if(name==='Pipeline'){s.setFrozenColumns(3);s.setColumnWidths(1,cols,135);s.setColumnWidth(1,185);s.setColumnWidth(3,165);s.setColumnWidth(6,230);s.setColumnWidth(12,250);s.setColumnWidth(14,290);s.getRange(2,8,rows-1,12).setBackground('#e6f3ff');s.getRange(2,1,rows-1,7).setBackground('#f0f3f7');var palettes={'New':['#dceafb','#174a7b'],'Contacted':['#ddf4f0','#086c68'],'Qualified':['#b8e6df','#065b51'],'Joined':['#087d85','#ffffff'],'Under review':['#dceafb','#174a7b'],'Clarification requested':['#fff0c7','#7c4b08'],'Discussion scheduled':['#d5ebfa','#155781'],'Accepted':['#b8e6df','#065b51'],'Active engagement':['#087d85','#ffffff'],'Completed':['#31516d','#ffffff'],'On hold':['#fff0c7','#7c4b08'],'Declined':['#f8dce0','#882c38'],'Not interested':['#f8dce0','#882c38'],'Closed':['#d9e0e8','#40556d']};var rules=s.getConditionalFormatRules().filter(rule=>{var c=rule.getBooleanCondition();return !(c&&c.getCriteriaType()===SpreadsheetApp.BooleanCriteria.TEXT_EQUAL_TO&&palettes[String(c.getCriteriaValues()[0])]&&rule.getRanges().every(r=>r.getColumn()===8&&r.getNumColumns()===1));});Object.entries(palettes).forEach(([status,c])=>rules.unshift(SpreadsheetApp.newConditionalFormatRule().whenTextEqualTo(status).setBackground(c[0]).setFontColor(c[1]).setRanges([s.getRange(2,8,Math.max(999,rows-1),1)]).build()));s.setConditionalFormatRules(rules);s.getRange('H1:S1').setBackground('#1768a6');}else{s.setColumnWidths(1,cols,name==='Read Me'?400:180);if(cols>1)s.setColumnWidth(2,name==='Settings'?350:name==='Read Me'?700:210);s.getRange(2,1,rows-1,cols).setBackground('#ffffff');if(name==='Settings')s.getRange('B2:B8').setBackground('#dceeff').setFontWeight('bold');}});
}
