/** Idempotent, clearly-labelled review fixtures. Never modifies non-sample decisions. */
function prepareCrmReview(){
 ['program','venture'].forEach(function(kind){CRM_CONTEXT_KIND_=kind;var book=crmBook_(kind),source=crmSource_(book,kind),existing=new Set(source.getDataRange().getValues().slice(1).map(r=>r[1]));
 if(kind==='program')source.getRange(1,16,1,5).setValues([['Terms version','Privacy version','Accepted UTC','Terms acknowledgement','Processing consent']]);var states=CRMCore.statuses[kind];states.forEach(function(status,i){var ref='SAMPLE-'+kind.toUpperCase()+'-'+String(i+1).padStart(3,'0');if(existing.has(ref))return;var received=new Date(Date.now()-(i*11+1)*86400000).toISOString();var row=kind==='program'?[received,ref,i%2?'Forward Deployment Engineering':'AI Engineering Training Internship','Sample learner '+(i+1),'sample'+i+'@example.com','12025550'+String(100+i),'Example College','Example degree','Working professional','Have built small projects','Flexible','AI Engineering Training Internship','Demonstration only','Sample only; no consent asserted','Sample','Sample','Sample',received,'Sample','Sample']:[received,ref,'Sample founder '+(i+1),'founder'+i+'@example.com','12025551'+String(100+i),'Example team','Sample idea '+(i+1),'Exploring a problem','Student team','Illustrative problem statement for CRM review','Example users','Illustrative approach','Sample evidence','Sample advisory request','','Non-confidential sample','Sample','Sample','Sample',received,'Sample','Sample'];source.getRange(source.getLastRow()+1,1,1,row.length).setNumberFormat('@').setValues([row]);});
 var pipe=book.getSheetByName('Pipeline'),blank=pipe.getDataRange().getValues();var end=blank.length-1;while(end>=1){if(blank[end].every(v=>v===''||v===false||v==null)){var start=end;while(start>1&&blank[start-1].every(v=>v===''||v===false||v==null))start--;pipe.deleteRows(start+1,end-start+1);end=start-1;}else end--;}var r=reconcileCrm_(kind);var rows=pipe.getDataRange().getValues();rows.forEach(function(row,i){if(i===0||String(row[0]).indexOf('SAMPLE-'+kind.toUpperCase()+'-')!==0||row[13])return;var n=Number(String(row[0]).split('-').pop())-1;pipe.getRange(i+1,8,1,12).setValues([[states[n],n%3?'Sample adviser':'',n%2?'Normal':'High',n?new Date(Date.now()-5*86400000):'',n%3?'Review sample next step':'',new Date(Date.now()+(n%3-1)*86400000),'Sample CRM scenario; not a real person or engagement','Sample review only',states[n]==='Active engagement'||states[n]==='Joined',kind==='venture'?CRMCore.stages[n%7]:'',kind==='venture'?'Example milestone':'','']]);});
 [11,13,19].forEach(c=>pipe.getRange(2,c,Math.max(pipe.getLastRow()-1,1),1).setNumberFormat(c===11?'yyyy-mm-dd hh:mm':'yyyy-mm-dd'));book.getSheetByName('Settings').getRange('B2').setValue('Live');refreshCrm();reviewRetention();
 ['Dashboard','Pipeline','Follow-ups','Activity','Source Responses','Settings','Read Me','Retention Review','Program Interests'].forEach(function(name,i){var s=book.getSheetByName(name);book.setActiveSheet(s);book.moveActiveSheet(i+1);});book.setActiveSheet(book.getSheetByName('Dashboard'));
 var read=book.getSheetByName('Read Me');read.setColumnWidth(1,210);read.setColumnWidth(2,780);read.getDataRange().setWrap(true);read.setRowHeights(2,read.getLastRow()-1,52);
 var settings=book.getSheetByName('Settings');settings.setColumnWidth(1,250);settings.setColumnWidth(2,320);settings.setRowHeights(1,settings.getLastRow(),32);
 console.log(kind+' CRM ready. Synthetic records excluded from Live.');
 });CRM_CONTEXT_KIND_='program';
}
