/* Pure reporting rules shared by Apps Script and local verification. No network or storage. */
var CRMCore=(function(){
 const statuses={program:['New','Contacted','Qualified','Joined','On hold','Not interested','Closed'],venture:['New','Under review','Clarification requested','Discussion scheduled','Accepted','Active engagement','Completed','On hold','Declined']};
 const stages=['Idea & opportunity','Customer validation','Business model','MVP planning','Pilot & launch','Measure & learn','Scale readiness'];
 const closed=['Joined','Not interested','Closed','Completed','Declined'];
 const day=86400000;
 function iso(value){if(!value)return '';const d=new Date(value);return Number.isNaN(+d)?'':d.toISOString();}
 function date(value){const v=iso(value);return v?new Date(+new Date(v)+19800000).toISOString().slice(0,10):'';}
 function text(v){return String(v==null?'':v).trim();}
 function normalize(r,kind){const x={...r};x.reference=text(r.reference);if(!x.reference)throw Error('Missing reference');x.received=iso(r.received);if(!x.received)throw Error('Invalid received timestamp: '+x.reference);x.kind=kind;x.status=statuses[kind].includes(r.status)?r.status:'New';x.email=text(r.email).replace(/^'/,'').toLowerCase();x.phone=text(r.phone).replace(/\D/g,'');x.mode=/^(sample|prototype|test)$/i.test(text(r.mode))?'Sample':'Live';x.programs=Array.from(new Set((Array.isArray(r.programs)?r.programs:text(r.programs).split(',')).map(text).filter(Boolean)));x.active=r.active===true||r.active==='TRUE';return x;}
 function reconcile(source,pipeline,kind){const records=pipeline.map(r=>({...r})),seen=new Map(),errors=[];records.forEach(r=>{if(seen.has(r.reference))errors.push('Duplicate pipeline reference: '+r.reference);seen.set(r.reference,r)});const sourceSeen=new Set();source.forEach(raw=>{try{const r=normalize(raw,kind);if(sourceSeen.has(r.reference)){errors.push('Duplicate source reference: '+r.reference);return}sourceSeen.add(r.reference);if(!seen.has(r.reference)){const n={...r,status:'New',owner:'',priority:'Normal',lastContact:'',nextAction:'',followUp:'',notes:'',reason:'',active:false,stage:kind==='venture'?stages[0]:'',milestone:'',target:'',updated:''};records.push(n);seen.set(r.reference,n)}}catch(e){errors.push(e.message)}});const emails=new Map(),phones=new Map();records.forEach(r=>{if(r.email)emails.set(r.email,(emails.get(r.email)||0)+1);if(r.phone)phones.set(r.phone,(phones.get(r.phone)||0)+1)});records.forEach(r=>r.repeat=Boolean((r.email&&emails.get(r.email)>1)||(r.phone&&phones.get(r.phone)>1)));return {records,errors};}
 function select(records,f){f=f||{};const seen=new Set();return records.filter(r=>{if(seen.has(r.reference))return false;seen.add(r.reference);const d=date(r.received);return r.mode===(f.mode||'Live')&&(!f.from||d>=f.from)&&(!f.to||d<=f.to)&&(!f.owner||f.owner==='All'||r.owner===f.owner)&&(!f.status||f.status==='All'||r.status===f.status)&&(!f.program||f.program==='All'||(r.programs||[]).includes(f.program))&&(!f.stage||f.stage==='All'||r.stage===f.stage)});}
 function due(r,now){if(closed.includes(r.status)||!r.followUp)return '';const d=/^\d{4}-\d{2}-\d{2}$/.test(r.followUp)?r.followUp:date(r.followUp);if(!d)return '';return d<date(now)?'Overdue':d===date(now)?'Due today':'';}
 function dashboard(records,f,kind,now){now=now||new Date().toISOString();const rows=select(records,f),counts=Object.fromEntries(statuses[kind].map(s=>[s,0])),months={},ages={'0–7 days':0,'8–30 days':0,'31–60 days':0,'61+ days':0};rows.forEach(r=>{counts[r.status]=(counts[r.status]||0)+1;const m=date(r.received).slice(0,7);months[m]=(months[m]||0)+1;if(!closed.includes(r.status)){const a=Math.max(0,Math.floor((+new Date(now)-+new Date(r.received))/day));ages[a<=7?'0–7 days':a<=30?'8–30 days':a<=60?'31–60 days':'61+ days']++}});const overdue=rows.filter(r=>due(r,now)==='Overdue').length;const metrics=kind==='program'?{'Total enquiries':rows.length,'New / uncontacted':rows.filter(r=>r.status==='New'&&!r.lastContact).length,Qualified:counts.Qualified,Joined:counts.Joined,'Follow-ups due':rows.filter(r=>due(r,now)).length,'Overdue follow-ups':overdue,'Conversion %':rows.length?Math.round(counts.Joined/rows.length*1000)/10:0}:{'Total ideas':rows.length,'Awaiting review':counts.New+counts['Under review'],'Awaiting clarification':counts['Clarification requested'],Accepted:counts.Accepted,'Active engagements':rows.filter(r=>r.active||r.status==='Active engagement').length,'Overdue follow-ups':overdue};return {metrics,counts,months:Object.fromEntries(Object.entries(months).sort()),ages,rows,refreshed:iso(now)};}
 function followups(records,now){return records.filter(r=>!closed.includes(r.status)).map(r=>({...r,flags:[due(r,now),!r.owner?'Needs owner':'',!r.nextAction?'Needs next step':''].filter(Boolean).join(' · ')})).filter(r=>r.flags).sort((a,b)=>String(a.followUp||'9999').localeCompare(String(b.followUp||'9999')));}
 function retention(records,now){return records.map(r=>{const active=r.active||['Joined','Active engagement'].includes(r.status);const base=r.lastContact?iso(r.lastContact):iso(r.received);const age=base?Math.floor((+new Date(now)-+new Date(base))/day):null;return {reference:r.reference,eligible:!active&&age!==null&&age>=90,reason:active?'Active engagement — separate terms':age===null?'Invalid date — manual review':age>=90?'90-day inactive boundary reached':'Within retention period',basis:base,days:age}});}
 function removeReferences(records,refs){const set=new Set(refs);return records.filter(r=>!set.has(r.reference));}
 function edit(record,field,value,kind,now,editor){const fields=['status','owner','priority','lastContact','nextAction','followUp','notes','reason','active','stage','milestone','target'];if(!fields.includes(field))throw Error('Read-only field');if(field==='status'&&!statuses[kind].includes(value))throw Error('Invalid status');if(field==='priority'&&!['Low','Normal','High'].includes(value))throw Error('Invalid priority');if(['lastContact','followUp','target'].includes(field)&&value&&!iso(value))throw Error('Invalid date');if(field==='stage'&&value&&!stages.includes(value))throw Error('Invalid stage');const updated={...record,[field]:value,updated:iso(now)};return {record:updated,activity:{reference:record.reference,at:iso(now),field,before:text(record[field]),after:text(value),editor:editor||'Unavailable'}};}
 return {statuses,stages,iso,date,normalize,reconcile,select,due,dashboard,followups,retention,removeReferences,edit};
})();

var CRM_PROGRAMS_=["AI Engineering Training Internship", "Forward Deployment Engineering", "Space Technology and Satellite Systems", "Machine Learning", "Full-Stack Development", "Forward Deployment Engineering for Leaders"];
/** Prepared only. Install this in a BOUND Apps Script project for each private workbook.
 * The intake project may include it too for immediate reconciliation after save.
 * No triggers, messages, sharing or retention deletion are enabled by this file.
 */
var CRM_COLUMNS_=['Reference','Received UTC','Name','Email','Phone','Programs / idea','Mode','Status','Assigned owner','Priority','Last contact','Next action','Next follow-up','Internal notes','Decision reason','Active engagement','Advisory stage','Next milestone','Target date','Updated UTC','Possible repeat'];
var CRM_KEYS_=['reference','received','name','email','phone','programs','mode','status','owner','priority','lastContact','nextAction','followUp','notes','reason','active','stage','milestone','target','updated','repeat'];
var CRM_CONTEXT_KIND_='';
function crmKind_(){if(CRM_CONTEXT_KIND_)return CRM_CONTEXT_KIND_;return PropertiesService.getScriptProperties().getProperty('CRM_KIND')==='venture'?'venture':'program';}
function crmBook_(kind){var p=PropertiesService.getScriptProperties(),id=p.getProperty(kind==='venture'?'VENTURE_SPREADSHEET_ID':'SPREADSHEET_ID');if(!id)throw Error('Configure the private spreadsheet ID first');return SpreadsheetApp.openById(id);}
function onOpen_(){SpreadsheetApp.getUi().createMenu('Academy CRM').addItem('Refresh CRM','refreshCrm_').addItem('Review retention (dry run)','reviewRetention_').addToUi();}
function crmSheet_(book,name){return book.getSheetByName(name)||book.insertSheet(name);}
function crmWrite_(sheet,headers,rows){sheet.clearContents();sheet.getRange(1,1,1,headers.length).setValues([headers]).setBackground('#102c56').setFontColor('#ffffff').setFontWeight('bold');if(rows.length)sheet.getRange(2,1,rows.length,headers.length).setNumberFormat('@').setValues(rows.map(r=>r.map(v=>typeof v==='boolean'?v:safeCell_(v==null?'':v))));sheet.setFrozenRows(1);sheet.setRowHeight(1,36);sheet.setTabColor('#205c99');}
function crmSource_(book,kind){var p=PropertiesService.getScriptProperties(),key=kind==='venture'?'VENTURE_SOURCE_SHEET':'SOURCE_SHEET',sheet=book.getSheetByName(p.getProperty(key)||'Source Responses')||book.getSheetByName('Enquiries');if(!sheet)throw Error('Source responses missing. Initialise intake first.');return sheet;}
function sourceRecords_(sheet,kind){var rows=sheet.getDataRange().getValues();return rows.slice(1).filter(r=>r[1]).map(r=>kind==='venture'?{received:r[0],reference:r[1],name:r[2],email:r[3],phone:r[4],programs:[r[6]],mode:r[16]}:{received:r[0],reference:r[1],name:r[3],email:r[4],phone:r[5],programs:String(r[2]||'').split(',').map(s=>s.trim()),mode:r[14]});}
function pipelineRecords_(sheet){if(sheet.getLastRow()<2)return [];return sheet.getRange(2,1,sheet.getLastRow()-1,CRM_KEYS_.length).getValues().filter(row=>String(row[0]||'').trim()).map(row=>{var r={};CRM_KEYS_.forEach((k,i)=>r[k]=row[i]);r.programs=String(r.programs).split(' | ').filter(Boolean);r.active=r.active===true||r.active==='TRUE';r.repeat=r.repeat===true||r.repeat==='TRUE';return r;});}
function pipelineRow_(r){return CRM_KEYS_.map(k=>k==='programs'?(r.programs||[]).join(' | '):r[k]==null?'':r[k]);}
function reconcileCrm_(kind){var book=crmBook_(kind),source=crmSource_(book,kind),sheet=crmSheet_(book,'Pipeline'),old=pipelineRecords_(sheet),result=CRMCore.reconcile(sourceRecords_(source,kind),old,kind);if(!sheet.getLastRow())crmWrite_(sheet,CRM_COLUMNS_,[]);var known=new Set(old.map(r=>r.reference));result.records.forEach(r=>{if(!known.has(r.reference)){sheet.getRange(sheet.getLastRow()+1,1,1,CRM_COLUMNS_.length).setNumberFormat('@').setValues([pipelineRow_(r).map(v=>typeof v==='boolean'?v:safeCell_(v))]);[11,13,19].forEach(c=>sheet.getRange(sheet.getLastRow(),c).setNumberFormat(c===11?'yyyy-mm-dd hh:mm':'yyyy-mm-dd'));known.add(r.reference)}});var p=PropertiesService.getScriptProperties();p.setProperty('CRM_ERROR_'+kind,result.errors.join('; ')||'');if(old.length){var current=sheet.getRange(2,1,Math.max(sheet.getLastRow()-1,1),1).getValues();var repeats=new Map(result.records.map(r=>[r.reference,r.repeat]));sheet.getRange(2,21,current.length,1).setValues(current.map(r=>[repeats.get(r[0])||false]));}return result;}
function setupCrm_(){var existing=crmBook_(crmKind_());if(!existing.getSheetByName('Settings')&&existing.getSheetByName('Pipeline')&&existing.getSheetByName('Activity')){reconcileCrm_(crmKind_());return;}var kind=crmKind_(),book=crmBook_(kind),source=crmSource_(book,kind);PropertiesService.getScriptProperties().setProperty(kind==='venture'?'VENTURE_SOURCE_SHEET':'SOURCE_SHEET',source.getName());if(source.getName()!=='Source Responses'){var mirror=crmSheet_(book,'Source Responses'),v=source.getDataRange().getValues();crmWrite_(mirror,v[0],v.slice(1));}
 ['Dashboard','Pipeline','Follow-ups','Activity','Settings','Read Me','Retention Review','Program Interests'].forEach(n=>crmSheet_(book,n));
 var settings=book.getSheetByName('Settings');if(!settings.getLastRow())crmWrite_(settings,['Setting','Value'],[['Mode','Live'],['Received from (IST date)',''],['Received to (IST date)',''],['Owner','All'],['Status','All'],['Program','All'],['Advisory stage','All']]);
 var activity=book.getSheetByName('Activity');if(!activity.getLastRow())crmWrite_(activity,['Reference','Changed UTC','Field','Previous value','New value','Editor'],[]);
 crmWrite_(book.getSheetByName('Read Me'),['Academy private CRM','How to use'],[['1. Dashboard','Use Settings filters then Academy CRM → Refresh CRM. Native charts show the selected received-date cohort.'],['2. Pipeline','Edit management columns H:S only. Sort the full table or use a filter view; never sort a single column.'],['3. Follow-ups','Review actions; no automatic email is sent.'],['4. Source','Original submissions are preserved. References identify records, never row numbers.'],['5. Privacy','File sharing controls access. Protection prevents accidental edits, not disclosure to authorised viewers.'],['6. Retention','Review is dry-run. Client must approve export/version-history handling before enabling deletion.'],['7. Activity','Install an on-edit trigger after approval. Identity may be unavailable; this is not a tamper-proof audit trail.'],['8. Accepted ideas','Accepted means suitable for further discussion, not a paid engagement or delivery commitment.'],['9. Time','Submission timestamps are UTC. Cohort dates and operational dates use Asia/Kolkata.'],['10. Filters','Data → Filter views lets each staff member filter Pipeline without changing colleagues’ views.'],['11. Samples','Live excludes Sample/Prototype records. Choose Sample explicitly for review.']]);
 book.setSpreadsheetTimeZone('Asia/Kolkata');reconcileCrm_(kind);var pipe=book.getSheetByName('Pipeline'),n=Math.max(pipe.getMaxRows()-1,1);
 function dropdown(col,values){pipe.getRange(2,col,n,1).setDataValidation(SpreadsheetApp.newDataValidation().requireValueInList(values,true).setAllowInvalid(false).build());}
 dropdown(8,CRMCore.statuses[kind]);dropdown(10,['Low','Normal','High']);dropdown(17,CRMCore.stages);pipe.getRange(2,16,n,1).setDataValidation(SpreadsheetApp.newDataValidation().requireCheckbox().build());[11,13,19].forEach(c=>pipe.getRange(2,c,n,1).setDataValidation(SpreadsheetApp.newDataValidation().requireDate().setAllowInvalid(false).build()).setNumberFormat(c===11?'yyyy-mm-dd hh:mm':'yyyy-mm-dd'));
 if(!pipe.getFilter())pipe.getRange(1,1,pipe.getMaxRows(),CRM_COLUMNS_.length).createFilter();pipe.setFrozenColumns(3);pipe.setColumnWidths(1,CRM_COLUMNS_.length,150);pipe.setColumnWidths(12,3,240);
 var rules=[SpreadsheetApp.newConditionalFormatRule().whenFormulaSatisfied('=AND($M2<>"",$M2<TODAY(),NOT(OR($H2="Joined",$H2="Closed",$H2="Not interested",$H2="Completed",$H2="Declined")))').setBackground('#ffebe7').setRanges([pipe.getRange(2,1,n,21)]).build(),SpreadsheetApp.newConditionalFormatRule().whenCellEmpty().setBackground('#fff3ce').setRanges([pipe.getRange(2,9,n,1),pipe.getRange(2,12,n,1)]).build()];pipe.setConditionalFormatRules(rules);
 settings.getRange('B2').setDataValidation(SpreadsheetApp.newDataValidation().requireValueInList(['Live','Sample'],true).setAllowInvalid(false).build());settings.getRange('B3:B4').setDataValidation(SpreadsheetApp.newDataValidation().requireDate().setAllowInvalid(false).build()).setNumberFormat('yyyy-mm-dd');
 refreshCrm_();protectCrm_(book);try{onOpen_();}catch(e){console.log('Open the workbook to use its bound menu after setup.');}
}
function protectCrm_(book){['Enquiries','Source Responses','Dashboard','Follow-ups','Activity','Program Interests','Retention Review'].forEach(name=>{var s=book.getSheetByName(name);if(!s)return;if(!s.getProtections(SpreadsheetApp.ProtectionType.SHEET).length){var p=s.protect().setDescription('Academy generated/source data');p.removeEditors(p.getEditors());if(p.canDomainEdit())p.setDomainEdit(false);}});var pipe=book.getSheetByName('Pipeline');if(!pipe.getProtections(SpreadsheetApp.ProtectionType.SHEET).length){var p=pipe.protect().setDescription('Edit management fields only');p.setUnprotectedRanges([pipe.getRange(2,8,pipe.getMaxRows()-1,12)]);p.removeEditors(p.getEditors());if(p.canDomainEdit())p.setDomainEdit(false);}}
function filters_(book){var v=book.getSheetByName('Settings').getRange('B2:B8').getValues().flat();return {mode:v[0]||'Live',from:v[1]?CRMCore.date(v[1]):'',to:v[2]?CRMCore.date(v[2]):'',owner:v[3],status:v[4],program:v[5],stage:v[6]};}
function refreshCrm_(){if(!crmBook_(crmKind_()).getSheetByName('Settings'))return reconcileCrm_(crmKind_());var lock=LockService.getScriptLock();if(!lock.tryLock(5000))throw Error('CRM busy; retry');try{var kind=crmKind_(),book=crmBook_(kind),result=reconcileCrm_(kind),records=result.records,now=new Date().toISOString(),d=CRMCore.dashboard(records,filters_(book),kind,now),sheet=book.getSheetByName('Dashboard');crmDashboardView_(book,kind,d,filters_(book),now,result.errors.length>0);
 crmWrite_(book.getSheetByName('Follow-ups'),['Reference','Name','Owner','Status','Next action','Follow-up','Attention'],CRMCore.followups(d.rows,now).map(r=>[r.reference,r.name,r.owner,r.status,r.nextAction,r.followUp,r.flags]));crmWrite_(book.getSheetByName('Program Interests'),['Reference','Program','Mode'],records.flatMap(r=>(r.programs||[]).map(p=>[r.reference,p,r.mode])));
 var original=crmSource_(book,kind);if(original.getName()!=='Source Responses'){var values=original.getDataRange().getValues();crmWrite_(book.getSheetByName('Source Responses'),values[0],values.slice(1));}
 var settings=book.getSheetByName('Settings');[[5,['All',...new Set(records.map(r=>r.owner).filter(Boolean))]],[6,['All',...CRMCore.statuses[kind]]],[7,['All',...new Set([...(kind==='program'?CRM_PROGRAMS_:[]),...records.flatMap(r=>r.programs||[])])]],[8,['All',...CRMCore.stages]]].forEach(([row,values])=>settings.getRange(row,2).setDataValidation(SpreadsheetApp.newDataValidation().requireValueInList(values,true).setAllowInvalid(false).build()));
 }finally{lock.releaseLock();}}
function crmOnEdit_(e){if(e&&e.source){CRM_CONTEXT_KIND_=e.source.getId()===PropertiesService.getScriptProperties().getProperty('VENTURE_SPREADSHEET_ID')?'venture':'program';if(e.range.getSheet().getName()==='Settings'){e.source.getSheetByName('Dashboard').getRange('A3').setValue('Filters changed — use Academy CRM → Refresh CRM');return;}}if(!e||e.range.getSheet().getName()!=='Pipeline')return;if(e.range.getRow()<2||e.range.getColumn()<8||e.range.getLastColumn()>19)return;var book=e.source,kind=crmKind_(),sheet=e.range.getSheet(),activity=book.getSheetByName('Activity'),editor='Unavailable';try{if(e.user)editor=e.user.getEmail()||'Unavailable';}catch(ignore){}var rows=e.range.getValues();rows.forEach((row,ri)=>{var at=e.range.getRow()+ri,ref=sheet.getRange(at,1).getValue();row.forEach((value,ci)=>activity.appendRow([ref,new Date().toISOString(),CRM_KEYS_[e.range.getColumn()+ci-1],rows.length===1&&row.length===1?safeCell_(e.oldValue==null?'':e.oldValue):'Unavailable (bulk edit)',safeCell_(value),editor||'Unavailable']));sheet.getRange(at,20).setValue(new Date().toISOString());});PropertiesService.getScriptProperties().setProperty('CRM_DIRTY_'+kind,'true');}
function reviewRetention_(){var kind=crmKind_(),book=crmBook_(kind),report=CRMCore.retention(pipelineRecords_(book.getSheetByName('Pipeline')),new Date().toISOString());crmWrite_(crmSheet_(book,'Retention Review'),['Reference','Eligible (dry run)','Reason','Retention basis UTC','Elapsed days'],report.map(r=>[r.reference,r.eligible,r.reason,r.basis,r.days]));}
function executeApprovedRetention_(){var p=PropertiesService.getScriptProperties();if(p.getProperty('RETENTION_ENABLED')!=='true'||p.getProperty('EXPORT_HISTORY_HANDLING_APPROVED')!=='true')throw Error('Retention remains dry-run pending client approval, export and version-history handling');var lock=LockService.getScriptLock();if(!lock.tryLock(5000))throw Error('CRM busy');try{var kind=crmKind_(),book=crmBook_(kind),refs=new Set(CRMCore.retention(pipelineRecords_(book.getSheetByName('Pipeline')),new Date().toISOString()).filter(r=>r.eligible).map(r=>r.reference));[['Enquiries',2],['Source Responses',2],['Pipeline',1],['Activity',1],['Program Interests',1],['Follow-ups',1],['Retention Review',1]].forEach(([name,col])=>{var s=book.getSheetByName(name);if(!s)return;var rows=s.getDataRange().getValues();for(var i=rows.length-1;i>=1;i--)if(refs.has(rows[i][col-1]))s.deleteRow(i+1);});}finally{lock.releaseLock();}refreshCrm_();}

/** Private Google Sheets dashboard presentation. No source records or staff decisions are changed. */
function crmDashboardView_(book,kind,d,filters,now,error){
 var sheet=book.getSheetByName('Dashboard'),navy='#112b49',blue='#1768a6',teal='#087d85',gold='#a76413',red='#ac3d49';
 sheet.getCharts().forEach(c=>sheet.removeChart(c));sheet.getRange(1,1,sheet.getMaxRows(),sheet.getMaxColumns()).breakApart();sheet.clear();sheet.setHiddenGridlines(true);sheet.setColumnWidths(1,15,74);sheet.setRowHeights(1,60,23);sheet.getRange('A1:O60').setBackground('#eef2f6').setFontFamily('Arial').setFontColor(navy).setVerticalAlignment('middle');
 function bar(range,text,bg,fg,size){return sheet.getRange(range).merge().setValue(text).setBackground(bg).setFontColor(fg).setFontSize(size).setFontWeight('bold');}
 bar('A1:O2',kind==='venture'?'  VENTURE IDEAS  /  ADVISORY PIPELINE':'  PROGRAM ENQUIRIES  /  ACADEMY CRM',navy,'#ffffff',22);
 bar('A3:O3','  '+String(filters.mode).toUpperCase()+' VIEW  •  '+Utilities.formatDate(new Date(now),'Asia/Kolkata','dd MMM yyyy, HH:mm')+' IST  •  '+(error?'RECONCILIATION NEEDS REVIEW':'DATA RECONCILED'),error?red:'#214e72','#ffffff',10);
 [['A4:C4','Pipeline'],['E4:G4','Follow-ups'],['I4:K4','Settings'],['M4:O4','Read Me']].forEach(([range,name])=>{var tab=book.getSheetByName(name);bar(range,'',navy,'#ffffff',11).setFormula('=HYPERLINK("#gid='+tab.getSheetId()+'","'+name+'  ↗")').setHorizontalAlignment('center');});
 var cards=Object.entries(d.metrics);cards.push(['Needs an owner',d.rows.filter(r=>!r.owner&&!['Joined','Closed','Not interested','Completed','Declined'].includes(r.status)).length]);if(kind==='venture')cards.push(['Follow-ups due',CRMCore.followups(d.rows,now).filter(r=>CRMCore.due(r,now)).length]);
 var hues=[navy,blue,teal,blue,teal,red,gold,navy];cards.slice(0,8).forEach(([label,value],i)=>{var row=6+Math.floor(i/4)*5,col=1+(i%4)*4,bg=hues[i];sheet.getRange(row,col,4,3).setBackground(bg).setFontColor('#ffffff');sheet.getRange(row,col,1,3).merge().setValue(label.toUpperCase()).setFontSize(9).setFontWeight('bold').setHorizontalAlignment('center');sheet.getRange(row+1,col,2,3).merge().setValue(value).setFontSize(32).setFontWeight('bold').setHorizontalAlignment('center').setNumberFormat(label==='Conversion %'?'0.0"%"':'0');sheet.getRange(row+3,col,1,3).merge().setValue(label==='Conversion %'?'Joined / selected unique enquiries':label==='Needs an owner'?'Open records without an owner':'Selected received-date cohort').setFontSize(8).setHorizontalAlignment('center');});
 bar('A16:O17','  Filters: '+[filters.from||'Any start',filters.to||'Any end',filters.owner||'All owners',filters.status||'All statuses',kind==='program'?filters.program||'All programs':filters.stage||'All stages'].join('  ·  ')+'\n  Change filters in Settings, then use Academy CRM → Refresh CRM. Live excludes sample records.','#ffffff',navy,10).setWrap(true).setFontWeight('normal');
 var data=book.getSheetByName('Dashboard Data')||book.insertSheet('Dashboard Data');data.clearContents();data.setHiddenGridlines(true);var detail={};d.rows.forEach(r=>{(kind==='venture'?[r.stage||'Not assigned']:(r.programs||[])).forEach(p=>detail[p]=(detail[p]||0)+1)});
 var charts=[['Current pipeline',d.counts,Charts.ChartType.PIE,19,1],['Monthly submissions',d.months,Charts.ChartType.COLUMN,19,9],['Age of unresolved records',d.ages,Charts.ChartType.BAR,33,1],[kind==='venture'?'Advisory stages':'Program interests',detail,Charts.ChartType.BAR,33,9]];
 charts.forEach((spec,i)=>{var entries=Object.entries(spec[1]),offset=1+i*35;data.getRange(offset,1,1,2).setValues([[spec[0],'Count']]);if(!entries.length||!entries.some(e=>e[1]>0)){bar(''+(i%2?'I':'A')+(spec[3]+2)+':'+(i%2?'O':'G')+(spec[3]+9),spec[0]+'\nNo records in the selected view','#ffffff','#60748b',14).setWrap(true).setHorizontalAlignment('center');return;}data.getRange(offset+1,1,entries.length,2).setValues(entries);var builder=sheet.newChart().setChartType(spec[2]).addRange(data.getRange(offset,1,entries.length+1,2)).setNumHeaders(1).setHiddenDimensionStrategy(Charts.ChartHiddenDimensionStrategy.SHOW_BOTH).setPosition(spec[3],spec[4],0,0).setOption('width',518).setOption('height',295).setOption('title',spec[0]).setOption('titleTextStyle',{color:navy,fontSize:15,bold:true}).setOption('fontName','Arial').setOption('backgroundColor','#ffffff').setOption('colors',[blue,teal,'#e2a83c','#527dc0','#31516d','#8db3cd',red]).setOption('legend',{position:i===0?'right':'none',textStyle:{fontSize:10,color:navy}});if(i===0)builder.setOption('pieHole',0.62).setOption('pieSliceText','value');sheet.insertChart(builder.build());});data.hideSheet();
 bar('A47:O48',kind==='program'?'Program-interest counts can include a person in more than one program. Overall totals count unique enquiry references.':'Accepted means suitable for further discussion. It does not automatically create a paid engagement or delivery commitment.','#ffffff','#52667e',10).setWrap(true).setFontWeight('normal');sheet.setFrozenRows(4);sheet.setTabColor(blue);
 crmStyleTables_(book,kind);
}
function crmStyleTables_(book,kind){
 ['Pipeline','Follow-ups','Activity','Settings','Read Me','Source Responses','Program Interests'].forEach(name=>{var s=book.getSheetByName(name);if(!s)return;var cols=s.getLastColumn(),rows=Math.max(2,s.getLastRow());s.setHiddenGridlines(true);s.setTabColor(name==='Pipeline'?'#1768a6':name==='Follow-ups'?'#ac3d49':name==='Settings'?'#a76413':'#087d85');s.getRange(1,1,rows,cols).setFontFamily('Arial').setFontSize(10).setVerticalAlignment('middle');s.getRange(1,1,1,cols).setBackground('#112b49').setFontColor('#ffffff').setFontWeight('bold').setWrap(true);s.setRowHeight(1,42);s.setRowHeights(2,rows-1,32);s.setFrozenRows(1);if(name==='Pipeline'){s.setFrozenColumns(3);s.setColumnWidths(1,cols,135);s.setColumnWidth(1,185);s.setColumnWidth(3,165);s.setColumnWidth(6,230);s.setColumnWidth(12,250);s.setColumnWidth(14,290);s.getRange(2,8,rows-1,12).setBackground('#e6f3ff');s.getRange(2,1,rows-1,7).setBackground('#f0f3f7');var palettes={'New':['#dceafb','#174a7b'],'Contacted':['#ddf4f0','#086c68'],'Qualified':['#b8e6df','#065b51'],'Joined':['#087d85','#ffffff'],'Under review':['#dceafb','#174a7b'],'Clarification requested':['#fff0c7','#7c4b08'],'Discussion scheduled':['#d5ebfa','#155781'],'Accepted':['#b8e6df','#065b51'],'Active engagement':['#087d85','#ffffff'],'Completed':['#31516d','#ffffff'],'On hold':['#fff0c7','#7c4b08'],'Declined':['#f8dce0','#882c38'],'Not interested':['#f8dce0','#882c38'],'Closed':['#d9e0e8','#40556d']};var rules=s.getConditionalFormatRules().filter(rule=>{var c=rule.getBooleanCondition();return !(c&&c.getCriteriaType()===SpreadsheetApp.BooleanCriteria.TEXT_EQUAL_TO&&palettes[String(c.getCriteriaValues()[0])]&&rule.getRanges().every(r=>r.getColumn()===8&&r.getNumColumns()===1));});Object.entries(palettes).forEach(([status,c])=>rules.unshift(SpreadsheetApp.newConditionalFormatRule().whenTextEqualTo(status).setBackground(c[0]).setFontColor(c[1]).setRanges([s.getRange(2,8,Math.max(999,rows-1),1)]).build()));s.setConditionalFormatRules(rules);s.getRange('H1:S1').setBackground('#1768a6');}else{s.setColumnWidths(1,cols,name==='Read Me'?400:180);if(cols>1)s.setColumnWidth(2,name==='Settings'?350:name==='Read Me'?700:210);s.getRange(2,1,rows-1,cols).setBackground('#ffffff');if(name==='Settings')s.getRange('B2:B8').setBackground('#dceeff').setFontWeight('bold');}});
}
