/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    'cms-users': CmsUserAuthOperations;
  };
  blocks: {};
  collections: {
    'cms-users': CmsUser;
    media: Media;
    faculty: Faculty;
    courses: Course;
    'course-change-requests': CourseChangeRequest;
    'course-modules': CourseModule;
    lessons: Lesson;
    'question-bank': QuestionBank;
    exams: Exam;
    'learning-path-definitions': LearningPathDefinition;
    posts: Post;
    webinars: Webinar;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'cms-users': CmsUsersSelect<false> | CmsUsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    faculty: FacultySelect<false> | FacultySelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    'course-change-requests': CourseChangeRequestsSelect<false> | CourseChangeRequestsSelect<true>;
    'course-modules': CourseModulesSelect<false> | CourseModulesSelect<true>;
    lessons: LessonsSelect<false> | LessonsSelect<true>;
    'question-bank': QuestionBankSelect<false> | QuestionBankSelect<true>;
    exams: ExamsSelect<false> | ExamsSelect<true>;
    'learning-path-definitions': LearningPathDefinitionsSelect<false> | LearningPathDefinitionsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    webinars: WebinarsSelect<false> | WebinarsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: CmsUser;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface CmsUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Internal SamkhyaAcademy content operators only. Learners and customer organization users never receive CMS access.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms-users".
 */
export interface CmsUser {
  id: string;
  name: string;
  roles: ('platform_admin' | 'content_admin' | 'internal_sme' | 'support')[];
  jobTitle?: string | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'cms-users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  caption?: string | null;
  assetType?:
    ('general' | 'course' | 'lesson' | 'lab' | 'project-package' | 'blog' | 'webinar' | 'faculty' | 'brochure') | null;
  copyrightNote?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faculty".
 */
export interface Faculty {
  id: string;
  name: string;
  slug: string;
  title: string;
  company?: string | null;
  experience?: string | null;
  bio?: string | null;
  photo?: (string | null) | Media;
  expertise?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Internal course catalog and authoring metadata. Use Modules, Lessons and Exams for granular content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: string;
  title: string;
  slug: string;
  shortDescription: string;
  description: string;
  category:
    | 'Artificial Intelligence'
    | 'Full-Stack Development'
    | 'Space Tech'
    | 'Data Analytics'
    | 'Cybersecurity'
    | 'Entrepreneurship'
    | 'Programming'
    | 'Soft Skills';
  /**
   * Protected setting. Content Admins propose changes through Course Change Requests.
   */
  contentType: 'FULL_ONLINE_VIDEOS' | 'HYBRID_OFFLINE_ONLINE' | 'FULL_OFFLINE';
  /**
   * Protected setting. Content Admins propose changes through Course Change Requests.
   */
  deliveryMode: 'SELF_PACED' | 'LIVE_ONLINE' | 'OFFLINE' | 'HYBRID' | 'COHORT';
  pricingCategory: 'FREE' | 'FREEMIUM' | 'PRICING';
  /**
   * Protected setting. Content Admins propose changes through Course Change Requests.
   */
  accessType: 'FREE' | 'PAID' | 'PRIVATE' | 'ORGANIZATION_ONLY';
  /**
   * Protected. Submit a Course Change Request for Platform Admin approval.
   */
  listPricePaise?: number | null;
  /**
   * Protected. Submit a Course Change Request for Platform Admin approval.
   */
  salePricePaise?: number | null;
  /**
   * Protected. Derived at publish time.
   */
  pricePaise?: number | null;
  /**
   * Protected. Submit a Course Change Request for Platform Admin approval.
   */
  freePreviewLessonCount?: number | null;
  currency?: string | null;
  level: 'Foundation' | 'Beginner' | 'Intermediate' | 'Advanced' | 'Executive' | 'Multi-level';
  durationText?: string | null;
  heroImage?: (string | null) | Media;
  brochure?: (string | null) | Media;
  /**
   * Optional static brochure path, e.g. /brochures/ai-engineering.pdf
   */
  brochurePublicPath?: string | null;
  faculty?: (string | Faculty)[] | null;
  outcomes?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  audience?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  prerequisites?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  tools?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Marketing/program-level journey stages used on premium course pages and brochures.
   */
  programJourney?:
    | {
        stage: string;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Language or platform tracks supported by the program. Useful for technology-agnostic programs such as FDE.
   */
  implementationTracks?:
    | {
        name: string;
        framework?: string | null;
        bestFor?: string | null;
        id?: string | null;
      }[]
    | null;
  signatureFramework?: {
    name?: string | null;
    tagline?: string | null;
    steps?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Optional venture-building workflow settings for entrepreneurship programs.
   */
  ventureBuilder?: {
    enabled?: boolean | null;
    mentorLed?: boolean | null;
    workflowLabel?: string | null;
    stageGateApprovalRequired?: boolean | null;
    /**
     * Optional operational guidance; not a hard enrollment limit.
     */
    cohortSizeGuidance?: number | null;
    stageArtifacts?:
      | {
          stageKey: string;
          artifactName: string;
          id?: string | null;
        }[]
      | null;
  };
  certificateEnabled?: boolean | null;
  completionRules?: {
    minLessonCompletionPct?: number | null;
    requiresPassingExam?: boolean | null;
    minExamPercent?: number | null;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Approval queue for protected commercial, access and delivery settings. Draft course content uses normal version review; these settings never apply without Platform Admin approval.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-change-requests".
 */
export interface CourseChangeRequest {
  id: string;
  title: string;
  course: string | Course;
  reason: string;
  /**
   * Only pricingCategory, accessType, contentType, deliveryMode, currency, preview count and price fields are accepted by the approval service.
   */
  proposedSettings:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'PENDING' | 'APPROVED' | 'REJECTED' | 'CANCELLED';
  requestedBy: string | CmsUser;
  reviewedBy?: (string | null) | CmsUser;
  reviewNote?: string | null;
  reviewedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-modules".
 */
export interface CourseModule {
  id: string;
  course: string | Course;
  title: string;
  description?: string | null;
  position: number;
  estimatedMinutes?: number | null;
  learningObjective?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons".
 */
export interface Lesson {
  id: string;
  module: string | CourseModule;
  title: string;
  slug: string;
  type: 'VIDEO' | 'ARTICLE' | 'LIVE_SESSION' | 'QUIZ' | 'ASSIGNMENT' | 'LAB' | 'DOWNLOAD';
  position: number;
  durationSec?: number | null;
  /**
   * When enabled, this lesson can be opened by preview-tier learners before purchase.
   */
  isFreePreview?: boolean | null;
  thumbnail?: (string | null) | Media;
  video?: (string | null) | Media;
  externalVideoUrl?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  labConfig?: {
    runtime?:
      | ('BROWSER_HTML' | 'BROWSER_JAVASCRIPT' | 'PYTHON_RUNNER' | 'NODE_RUNNER' | 'JAVA_RUNNER' | 'DOTNET_RUNNER')
      | null;
    instructions: string;
    starterFiles?:
      | {
          path: string;
          language: string;
          content: string;
          readOnly?: boolean | null;
          id?: string | null;
        }[]
      | null;
    hints?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    successChecks?:
      | {
          label: string;
          kind: 'DOM_SELECTOR' | 'TEXT_PRESENT' | 'CONSOLE_OUTPUT' | 'UNIT_TEST' | 'MANUAL_REVIEW';
          assertion: string;
          weight?: number | null;
          id?: string | null;
        }[]
      | null;
    previewMode?: ('SPLIT' | 'EDITOR_ONLY' | 'OUTPUT_ONLY') | null;
    allowDownload?: boolean | null;
    /**
     * Browser labs run in an isolated iframe. Server runtimes must be delegated to a governed runner adapter.
     */
    executionPolicy?: string | null;
  };
  projectConfig?: {
    brief: string | Media;
    packageZip: string | Media;
    previewGif?: (string | null) | Media;
    repositoryUrl?: string | null;
    /**
     * Human-readable project folder architecture included in the learner preview.
     */
    fileTree: string;
    setupInstructions: string;
    milestones?:
      | {
          title: string;
          description: string;
          estimatedMinutes?: number | null;
          id?: string | null;
        }[]
      | null;
    rubric?:
      | {
          criterion: string;
          description: string;
          points: number;
          id?: string | null;
        }[]
      | null;
  };
  resources?:
    | {
        label: string;
        file?: (string | null) | Media;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  allowComments?: boolean | null;
  allowReactions?: boolean | null;
  completionMode?:
    | ('MANUAL' | 'MANUAL_OR_90_PERCENT_VIDEO' | 'RESOURCE_OPEN' | 'EXAM_PASS' | 'LAB_COMPLETE' | 'PROJECT_SUBMISSION')
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "question-bank".
 */
export interface QuestionBank {
  id: string;
  course: string | Course;
  module?: (string | null) | CourseModule;
  lesson?: (string | null) | Lesson;
  type: 'SINGLE_CHOICE' | 'MULTI_SELECT' | 'TRUE_FALSE' | 'SHORT_TEXT';
  difficulty?: ('EASY' | 'MEDIUM' | 'HARD') | null;
  prompt: string;
  options?:
    | {
        key: string;
        label: string;
        isCorrect?: boolean | null;
        id?: string | null;
      }[]
    | null;
  answerText?: string | null;
  explanation?: string | null;
  points?: number | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exams".
 */
export interface Exam {
  id: string;
  course: string | Course;
  title: string;
  description?: string | null;
  examType?: ('PRACTICE' | 'MODULE' | 'COURSE_FINAL' | 'CERTIFICATION') | null;
  passPercent?: number | null;
  timeLimitMin?: number | null;
  maxAttempts?: number | null;
  randomizeQuestions?: boolean | null;
  randomizeOptions?: boolean | null;
  /**
   * If set, sample this many questions from the selected pool.
   */
  questionCount?: number | null;
  questions: (string | QuestionBank)[];
  showAnswersAfterSubmit?: boolean | null;
  certificateTrigger?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "learning-path-definitions".
 */
export interface LearningPathDefinition {
  id: string;
  title: string;
  slug: string;
  description?: string | null;
  audience?: string | null;
  items?:
    | {
        course: string | Course;
        required?: boolean | null;
        milestoneLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * CMS-managed blog, insight, announcement and thought-leadership content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  slug: string;
  excerpt: string;
  heroImage?: (string | null) | Media;
  author?: (string | null) | Faculty;
  category:
    | 'AI & Agentic Systems'
    | 'Full-Stack'
    | 'Enterprise Technology'
    | 'Data & Analytics'
    | 'Cybersecurity'
    | 'Space Tech'
    | 'Entrepreneurship'
    | 'Learning & Careers';
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedCourses?: (string | Course)[] | null;
  relatedWebinar?: (string | null) | Webinar;
  publishedAt?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    canonicalUrl?: string | null;
    ogImage?: (string | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webinars".
 */
export interface Webinar {
  id: string;
  title: string;
  slug: string;
  summary: string;
  startsAt: string;
  durationMin: number;
  format: 'ONLINE' | 'OFFLINE' | 'HYBRID';
  location?: string | null;
  meetingUrl?: string | null;
  capacity?: number | null;
  heroImage?: (string | null) | Media;
  speakers?: (string | Faculty)[] | null;
  relatedCourses?: (string | Course)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  slug: string;
  pageType?: ('LANDING' | 'CAMPAIGN' | 'ABOUT' | 'POLICY') | null;
  blocks?:
    | (
        | {
            eyebrow?: string | null;
            heading: string;
            body?: string | null;
            buttonLabel: string;
            href: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaSection';
          }
        | {
            items?:
              | {
                  image: string | Media;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageGallery';
          }
        | {
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            course: string | Course;
            headline?: string | null;
            ctaLabel?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'coursePromo';
          }
        | {
            webinar: string | Webinar;
            headline?: string | null;
            ctaLabel?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'webinarPromo';
          }
      )[]
    | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'cms-users';
        value: string | CmsUser;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'faculty';
        value: string | Faculty;
      } | null)
    | ({
        relationTo: 'courses';
        value: string | Course;
      } | null)
    | ({
        relationTo: 'course-change-requests';
        value: string | CourseChangeRequest;
      } | null)
    | ({
        relationTo: 'course-modules';
        value: string | CourseModule;
      } | null)
    | ({
        relationTo: 'lessons';
        value: string | Lesson;
      } | null)
    | ({
        relationTo: 'question-bank';
        value: string | QuestionBank;
      } | null)
    | ({
        relationTo: 'exams';
        value: string | Exam;
      } | null)
    | ({
        relationTo: 'learning-path-definitions';
        value: string | LearningPathDefinition;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'webinars';
        value: string | Webinar;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'cms-users';
    value: string | CmsUser;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'cms-users';
    value: string | CmsUser;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms-users_select".
 */
export interface CmsUsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  jobTitle?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  assetType?: T;
  copyrightNote?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faculty_select".
 */
export interface FacultySelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  title?: T;
  company?: T;
  experience?: T;
  bio?: T;
  photo?: T;
  expertise?:
    | T
    | {
        label?: T;
        id?: T;
      };
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  description?: T;
  category?: T;
  contentType?: T;
  deliveryMode?: T;
  pricingCategory?: T;
  accessType?: T;
  listPricePaise?: T;
  salePricePaise?: T;
  pricePaise?: T;
  freePreviewLessonCount?: T;
  currency?: T;
  level?: T;
  durationText?: T;
  heroImage?: T;
  brochure?: T;
  brochurePublicPath?: T;
  faculty?: T;
  outcomes?:
    | T
    | {
        text?: T;
        id?: T;
      };
  audience?:
    | T
    | {
        text?: T;
        id?: T;
      };
  prerequisites?:
    | T
    | {
        text?: T;
        id?: T;
      };
  tools?:
    | T
    | {
        name?: T;
        id?: T;
      };
  programJourney?:
    | T
    | {
        stage?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  implementationTracks?:
    | T
    | {
        name?: T;
        framework?: T;
        bestFor?: T;
        id?: T;
      };
  signatureFramework?:
    | T
    | {
        name?: T;
        tagline?: T;
        steps?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  ventureBuilder?:
    | T
    | {
        enabled?: T;
        mentorLed?: T;
        workflowLabel?: T;
        stageGateApprovalRequired?: T;
        cohortSizeGuidance?: T;
        stageArtifacts?:
          | T
          | {
              stageKey?: T;
              artifactName?: T;
              id?: T;
            };
      };
  certificateEnabled?: T;
  completionRules?:
    | T
    | {
        minLessonCompletionPct?: T;
        requiresPassingExam?: T;
        minExamPercent?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-change-requests_select".
 */
export interface CourseChangeRequestsSelect<T extends boolean = true> {
  title?: T;
  course?: T;
  reason?: T;
  proposedSettings?: T;
  status?: T;
  requestedBy?: T;
  reviewedBy?: T;
  reviewNote?: T;
  reviewedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-modules_select".
 */
export interface CourseModulesSelect<T extends boolean = true> {
  course?: T;
  title?: T;
  description?: T;
  position?: T;
  estimatedMinutes?: T;
  learningObjective?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons_select".
 */
export interface LessonsSelect<T extends boolean = true> {
  module?: T;
  title?: T;
  slug?: T;
  type?: T;
  position?: T;
  durationSec?: T;
  isFreePreview?: T;
  thumbnail?: T;
  video?: T;
  externalVideoUrl?: T;
  content?: T;
  labConfig?:
    | T
    | {
        runtime?: T;
        instructions?: T;
        starterFiles?:
          | T
          | {
              path?: T;
              language?: T;
              content?: T;
              readOnly?: T;
              id?: T;
            };
        hints?:
          | T
          | {
              text?: T;
              id?: T;
            };
        successChecks?:
          | T
          | {
              label?: T;
              kind?: T;
              assertion?: T;
              weight?: T;
              id?: T;
            };
        previewMode?: T;
        allowDownload?: T;
        executionPolicy?: T;
      };
  projectConfig?:
    | T
    | {
        brief?: T;
        packageZip?: T;
        previewGif?: T;
        repositoryUrl?: T;
        fileTree?: T;
        setupInstructions?: T;
        milestones?:
          | T
          | {
              title?: T;
              description?: T;
              estimatedMinutes?: T;
              id?: T;
            };
        rubric?:
          | T
          | {
              criterion?: T;
              description?: T;
              points?: T;
              id?: T;
            };
      };
  resources?:
    | T
    | {
        label?: T;
        file?: T;
        url?: T;
        id?: T;
      };
  allowComments?: T;
  allowReactions?: T;
  completionMode?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "question-bank_select".
 */
export interface QuestionBankSelect<T extends boolean = true> {
  course?: T;
  module?: T;
  lesson?: T;
  type?: T;
  difficulty?: T;
  prompt?: T;
  options?:
    | T
    | {
        key?: T;
        label?: T;
        isCorrect?: T;
        id?: T;
      };
  answerText?: T;
  explanation?: T;
  points?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exams_select".
 */
export interface ExamsSelect<T extends boolean = true> {
  course?: T;
  title?: T;
  description?: T;
  examType?: T;
  passPercent?: T;
  timeLimitMin?: T;
  maxAttempts?: T;
  randomizeQuestions?: T;
  randomizeOptions?: T;
  questionCount?: T;
  questions?: T;
  showAnswersAfterSubmit?: T;
  certificateTrigger?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "learning-path-definitions_select".
 */
export interface LearningPathDefinitionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  audience?: T;
  items?:
    | T
    | {
        course?: T;
        required?: T;
        milestoneLabel?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  heroImage?: T;
  author?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  content?: T;
  relatedCourses?: T;
  relatedWebinar?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalUrl?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webinars_select".
 */
export interface WebinarsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  startsAt?: T;
  durationMin?: T;
  format?: T;
  location?: T;
  meetingUrl?: T;
  capacity?: T;
  heroImage?: T;
  speakers?: T;
  relatedCourses?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  pageType?: T;
  blocks?:
    | T
    | {
        ctaSection?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              buttonLabel?: T;
              href?: T;
              id?: T;
              blockName?: T;
            };
        imageGallery?:
          | T
          | {
              items?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        coursePromo?:
          | T
          | {
              course?: T;
              headline?: T;
              ctaLabel?: T;
              id?: T;
              blockName?: T;
            };
        webinarPromo?:
          | T
          | {
              webinar?: T;
              headline?: T;
              ctaLabel?: T;
              id?: T;
              blockName?: T;
            };
      };
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'courses';
          value: string | Course;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null)
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null);
    global?: string | null;
    user?: (string | null) | CmsUser;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}