from pathlib import Path
import json
options={'internship':'AI Engineering Training Internship','fde':'Forward Deployment Engineering','space':'Space Technology and Satellite Systems','ml':'Machine Learning','fullstack':'Full-Stack Development','leadership':'Forward Deployment Engineering for Leaders'}
Path('src/content/program-options.json').write_text(json.dumps(options,indent=2)+'\n')
p=Path('integrations/google-apps-script/Code.gs');s=p.read_text(encoding='utf-8');s="var PROGRAM_OPTIONS_="+json.dumps(options)+";\n"+s
old="e&&e.parameter&&e.parameter.program==='space'?'space':e&&e.parameter&&e.parameter.program==='fde'?'fde':e&&e.parameter&&e.parameter.program==='internship'?'internship':''"
s=s.replace(old,"e&&e.parameter&&Object.prototype.hasOwnProperty.call(PROGRAM_OPTIONS_,e.parameter.program)?e.parameter.program:''")
s=s.replace("return x==='AI Engineering Training Internship'||x==='Forward Deployment Engineering'||x==='Space Technology and Satellite Systems';","return Object.values(PROGRAM_OPTIONS_).indexOf(x)>=0;")
s=s.replace("var interests=['Space Technology", "var interests=['Machine Learning','Full-Stack Development','Forward Deployment Engineering for Leaders','Space Technology")
s=s.replace("'Job seeker','Other'","'Job seeker','Leadership / business role','Other'").replace("'Experienced software engineer']","'Experienced software engineer','Prefer a non-coding leadership track']")
p.write_text(s,encoding='utf-8')
p=Path('integrations/google-apps-script/Form.template.html');s=p.read_text(encoding='utf-8');at=s.index('const selectedProgram=');end=s.index('\n',at);s=s[:at]+"const programOptions="+json.dumps(options)+";const selectedProgram=settings.selectedProgram||new URLSearchParams(location.search).get('program');if(programOptions[selectedProgram]){const input=[...document.querySelectorAll('input[name=interests]')].find(el=>el.value===programOptions[selectedProgram]);if(input)input.checked=true;}\n"+s[end+1:]
needle='<label class="choice"><input type="checkbox" name="interests" value="RAG and document assistants">'
new=''.join('<label class="choice"><input type="checkbox" name="interests" value="'+options[key]+'">'+options[key]+'</label>' for key in ['ml','fullstack','leadership'])
s=s.replace(needle,new+needle).replace('Degree / course *','Education / professional background *').replace('For example, B.E. Computer Science','For example, degree or current role').replace('<option>Job seeker</option>','<option>Job seeker</option><option>Leadership / business role</option>').replace('<option>Experienced software engineer</option>','<option>Experienced software engineer</option><option>Prefer a non-coding leadership track</option>').replace('Ask about the next batch, fees, timetable, or the skills you’ll build.','Ask about fees and learning goals. For Full-Stack Development, mention MEAN, Python, .NET or Java if you have a preference.')
p.write_text(s,encoding='utf-8')
p=Path('src/pages/enquire.astro');s=p.read_text(encoding='utf-8').replace('Ask about the AI Engineering Training Internship Forward Deployment Engineering or Space Technology, batch arrangements, and how to join.','Enquire about AI engineering, machine learning, full-stack development, space technology or FDE leadership. Discuss your background and learning goals.').replace('Ask about the AI internship, Forward Deployment Engineering or a space-tech learning experience for your college team. Share your background, goals and questions.','Explore AI engineering, machine learning, full-stack development, space technology or FDE leadership. Share your experience, goals and preferred learning path.').replace('<script>\nconst frame','<script>\nimport programOptions from \'../content/program-options.json\';\nconst frame').replace("if(selected==='fde'||selected==='internship'||selected==='space')","if(selected&&Object.prototype.hasOwnProperty.call(programOptions,selected))")
p.write_text(s,encoding='utf-8')
p=Path('integrations/google-apps-script/Crm.gs');s=p.read_text(encoding='utf-8');s='var CRM_PROGRAMS_='+json.dumps(list(options.values()))+';\n'+s;s=s.replace("['All',...new Set(records.flatMap(r=>r.programs||[]))]","['All',...new Set([...(kind==='program'?CRM_PROGRAMS_:[]),...records.flatMap(r=>r.programs||[])])]");p.write_text(s,encoding='utf-8')
p=Path('src/data/seo.ts');s=p.read_text(encoding='utf-8');s="import {extendedPrograms} from './extendedPrograms';\n"+s;s=s.replace("const names:Record<string,string>={", "const names:Record<string,string>={...Object.fromEntries(extendedPrograms.map(p=>[`/programs/${p.slug}/`,p.title])),");p.write_text(s,encoding='utf-8')
