from pathlib import Path
import json
p=Path('src/data/extendedPrograms.ts');p.write_text('''import {z} from 'astro/zod';
import ml from '../content/extended-programs/ml.json';
import fullstack from '../content/extended-programs/fullstack.json';
import leadership from '../content/extended-programs/leadership.json';
const text=z.string().min(1),list=z.array(text).min(1);
const schema=z.object({key:z.enum(['ml','fullstack','leadership']),slug:text,title:text,shortTitle:text,image:text,headline:text,intro:text,audience:text,bridge:text,scope:text,tags:list,paths:z.array(z.tuple([text,text])),modules:z.array(z.object({title:text,icon:text,summary:text,topics:list,tools:list,practice:text,deliverables:list,criteria:list})).min(4),projects:z.array(z.object({title:text,icon:text,problem:text,flow:list,practice:text,failures:list,evidence:list})).length(3),preparation:z.array(z.tuple([text,text])).min(4)});
export const extendedPrograms=[ml,fullstack,leadership].map(p=>schema.parse(p));
export type ExtendedProgram=(typeof extendedPrograms)[number];
''',encoding='utf-8')
p=Path('src/data/programs.ts');s=p.read_text(encoding='utf-8').replace("const programSchema", "import {extendedPrograms} from './extendedPrograms';\nconst programSchema");s=s.replace("href:'/enquire/'","href:'/enquire/?program=internship'");s=s.replace('export const tracks = {','const existingTracks = {');s=s.replace('export type Track = keyof typeof tracks;',"export const tracks={...existingTracks,...Object.fromEntries(extendedPrograms.map(p=>[p.key,programSchema.parse({title:p.title,shortTitle:p.shortTitle,slug:p.slug,audience:p.audience,status:'upcoming',enquiry:{state:'open',href:'/enquire/?program='+p.key}})]))} as Record<'internship'|'fde'|'space'|'ml'|'fullstack'|'leadership',z.infer<typeof programSchema>>;\nexport type Track = keyof typeof tracks;");p.write_text(s,encoding='utf-8')
p=Path('src/data/catalog.ts');s=p.read_text(encoding='utf-8');s="import {extendedPrograms} from './extendedPrograms';\n"+s+s[s.index('') :0];s+='\nfor(const p of extendedPrograms)catalog[`/programs/${p.slug}/`]={label:p.audience.toUpperCase(),facts:[`${p.modules.length} curriculum modules`,p.key===\'leadership\'?\'Three leadership exercises\':\'Three portfolio projects\'],tags:p.tags,cta:\'Enquire about this program\',href:\'/enquire/?program=\'+p.key};\n';p.write_text(s,encoding='utf-8')
for p in Path('src/content/extended-programs').glob('*.json'):
 d=json.loads(p.read_text(encoding='utf-8'));Path('src/content/programs/'+d['slug']+'.md').write_text('---\n'+ '\n'.join([f'title: {d["title"]}','status: upcoming',f'href: /programs/{d["slug"]}/',f'image: {d["image"]}','duration: Confirm through enquiry',f'audience: {d["audience"]}','effort: Confirm through enquiry',f'summary: {d["intro"]}'])+'\n---\n\nDetailed content is maintained in src/content/extended-programs/'+d['key']+'.json.\n',encoding='utf-8')
p=Path('src/layouts/ProgramLayout.astro');s=p.read_text(encoding='utf-8');a=s.index('<nav class="track-switch"');b=s.index('</nav>',a)+6;s=s[:a]+'''<details class="track-picker"><summary><Icon name="layers" />Switch program<Icon name="chevron" /></summary><nav class="track-switch" aria-label="Choose your learning track">{(Object.keys(tracks) as Track[]).map(key=><a href={programUrl(key,section)} aria-current={key===track?'true':undefined}><Icon name={key==='leadership'?'users':key==='space'?'satellite':'code'}/>{tracks[key].shortTitle}</a>)}</nav></details>'''+s[b:];s=s.replace('{item.label}</a>','{track===\'leadership\'&&item.id===\'career-preparation\'?\'Leadership preparation\':item.label}</a>');s+='''\n<style>.track-picker{position:relative;min-width:210px;z-index:5}.track-picker summary{display:flex;gap:10px;align-items:center;cursor:pointer;list-style:none;border:1px solid #e0e4ee;border-radius:9px;padding:10px 14px;font-size:.78rem;color:#23385d;background:#fff}.track-picker summary::-webkit-details-marker{display:none}.track-picker .track-switch{position:absolute;right:0;top:100%;width:320px;max-width:90vw;display:flex;flex-direction:column;align-items:stretch;background:white;box-shadow:0 12px 30px #16345b20;padding:10px;border:1px solid #e0e4ee;border-radius:10px}.track-picker .track-switch a{justify-content:flex-start;font-size:.75rem;padding:10px;min-height:42px}.track-picker summary:focus-visible{outline:3px solid #6550df;outline-offset:3px}@media(max-width:850px){.track-picker{width:100%}.track-picker .track-switch{position:static;width:100%;max-width:none;box-shadow:none;margin-top:8px}}</style>\n''';p.write_text(s,encoding='utf-8')
p=Path('site.config.mjs');s=p.read_text(encoding='utf-8').replace("'space-technology'].flatMap", "'space-technology', 'machine-learning', 'full-stack-development', 'fde-for-leaders'].flatMap");p.write_text(s,encoding='utf-8')
p=Path('src/components/Art.astro');s=p.read_text(encoding='utf-8').replace("(name === 'learning-studio' || name === 'venture-studio')", "(['learning-studio','venture-studio','ai-engineering','fde-learning','space-tech','machine-learning','full-stack','ai-leadership'].includes(name))");p.write_text(s,encoding='utf-8')
for p in Path('src/pages/programs/forward-deployment-engineer').glob('*.astro'):
 s=p.read_text(encoding='utf-8').replace('image="full-stack"','image="fde-learning"').replace('image="ai-engineering"','image="fde-learning"');p.write_text(s,encoding='utf-8')
p=Path('src/content/programs/forward-deployment-engineer.md');s=p.read_text(encoding='utf-8').replace('image: full-stack','image: fde-learning');p.write_text(s,encoding='utf-8')
p=Path('src/pages/programs/ai-engineering-internship/index.astro');s=p.read_text(encoding='utf-8').replace('image="learning-studio"','image="ai-engineering"');p.write_text(s,encoding='utf-8')
