'use client'
import { useState } from 'react'

export function CrmLeadActions({leadId,courses}:{leadId:string,courses:{id:string,title:string}[]}){
 const [message,setMessage]=useState('')
 async function updateStatus(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const status=String(f.get('status'));const next=String(f.get('nextFollowUpAt')||'');const body:any={status};if(next) body.nextFollowUpAt=new Date(next).toISOString();const r=await fetch(`/api/admin/crm/leads/${leadId}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(body)});setMessage(r.ok?'Lead updated':'Update failed');if(r.ok) location.reload()}
 async function addActivity(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const r=await fetch('/api/admin/crm/activities',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({leadId,type:String(f.get('type')),subject:String(f.get('subject')),notes:String(f.get('notes')||'')})});setMessage(r.ok?'Activity saved':'Could not save activity');if(r.ok) location.reload()}
 async function createOffer(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const original=Math.round(Number(f.get('original'))*100);const custom=Math.round(Number(f.get('custom'))*100);const expires=String(f.get('expiresAt')||'');const payload:any={leadId,courseId:String(f.get('courseId')),originalAmountPaise:original,discountType:'CUSTOM_PRICE',customPricePaise:custom,maxRedemptions:1};if(expires) payload.expiresAt=new Date(expires).toISOString();const r=await fetch('/api/admin/offers',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const j=await r.json();if(r.ok){setMessage(`Share link: ${j.shareUrl}`);navigator.clipboard?.writeText(j.shareUrl)}else setMessage(j.error||'Offer failed')}

 async function sendMessage(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const channel=String(f.get('channel'));const payload:any={leadId,channel,subject:String(f.get('subject')||''),message:String(f.get('message')||''),whatsappTemplate:String(f.get('whatsappTemplate')||'')};const r=await fetch('/api/admin/crm/communications/send',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const j=await r.json();setMessage(r.ok?`${channel} sent/logged`:j.error||'Message failed')}
 return <div className="grid" style={{gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))'}}>
  <form className="card" onSubmit={updateStatus}><h3>Lead status</h3><label>Status<select name="status" defaultValue="CONTACTED"><option>NEW</option><option>CONTACTED</option><option>QUALIFIED</option><option>COUNSELLING</option><option>APPLICATION</option><option>PAYMENT_PENDING</option><option>ENROLLED</option><option>LOST</option></select></label><label>Next follow-up<input name="nextFollowUpAt" type="datetime-local"/></label><button className="btn primary">Update</button></form>
  <form className="card" onSubmit={addActivity}><h3>Add activity</h3><label>Type<select name="type"><option>CALL</option><option>WHATSAPP</option><option>EMAIL</option><option>MEETING</option><option>NOTE</option></select></label><label>Subject<input name="subject" required/></label><label>Notes<textarea name="notes" rows={3}/></label><button className="btn primary">Save activity</button></form>

  <form className="card" onSubmit={sendMessage}><h3>Contact lead</h3><label>Channel<select name="channel"><option>WHATSAPP</option><option>EMAIL</option></select></label><label>Email subject<input name="subject" placeholder="SamkhyaAcademy course update"/></label><label>WhatsApp approved template<input name="whatsappTemplate" placeholder="academy_direct_followup"/></label><label>Message<textarea name="message" rows={4} required/></label><button className="btn primary">Send</button><p className="muted">Requires opt-in consent for the selected channel.</p></form>
  <form className="card" onSubmit={createOffer}><h3>Create private payment offer</h3><label>Course<select name="courseId">{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label>Regular price ₹<input name="original" type="number" min="1" required/></label><label>Offer price ₹<input name="custom" type="number" min="1" required/></label><label>Expires<input name="expiresAt" type="datetime-local"/></label><button className="btn primary">Create Razorpay link</button><p className="muted">Generates a SamkhyaAcademy share URL backed by a Razorpay Payment Link.</p></form>
  {message&&<div className="card"><strong>{message}</strong></div>}
 </div>
}
