'use client'
import {useState} from 'react'

type Template={id:string;name:string;key:string;channel:'EMAIL'|'WHATSAPP';status:string;providerTemplateName?:string|null}
type Campaign={id:string;name:string;channel:string;status:string;stats?:any;template:{name:string};_count:{recipients:number}}
export function MarketingConsole({templates,campaigns}:{templates:Template[];campaigns:Campaign[]}){
 const[msg,setMsg]=useState('')
 async function createTemplate(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const channel=String(f.get('channel'));const payload:any={name:f.get('name'),key:f.get('key'),channel,subject:f.get('subject')||undefined,bodyText:f.get('bodyText'),bodyHtml:f.get('bodyHtml')||undefined,providerTemplateName:f.get('providerTemplateName')||undefined,providerLanguage:'en',status:'ACTIVE',variables:channel==='WHATSAPP'?{bodyParameters:['name','program']}:{}};const r=await fetch('/api/admin/crm/communications/templates',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});setMsg(r.ok?'Template created':'Could not create template');if(r.ok)location.reload()}
 async function createCampaign(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const statuses=String(f.get('statuses')||'').split(',').map(x=>x.trim()).filter(Boolean);const programSlugs=String(f.get('programSlugs')||'').split(',').map(x=>x.trim()).filter(Boolean);const template=templates.find(t=>t.id===String(f.get('templateId')));if(!template)return;const payload={name:f.get('name'),channel:template.channel,templateId:template.id,segment:{statuses,programSlugs,limit:Number(f.get('limit')||500)}};const r=await fetch('/api/admin/crm/communications/campaigns',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});setMsg(r.ok?'Campaign created':'Could not create campaign');if(r.ok)location.reload()}
 async function send(id:string){if(!confirm('Send this campaign now to opted-in recipients?'))return;setMsg('Sending…');const r=await fetch(`/api/admin/crm/communications/campaigns/${id}/send`,{method:'POST'});const j=await r.json();setMsg(r.ok?`Completed: ${j.sent} sent, ${j.skipped} skipped, ${j.failed} failed`:j.error||'Send failed');if(r.ok)setTimeout(()=>location.reload(),1000)}
 return <div className="grid" style={{gap:20}}>
  <section className="card"><h2>Communication templates</h2><p className="muted">Email templates are sent with Amazon SES. WhatsApp campaigns use approved Meta WhatsApp templates.</p><form onSubmit={createTemplate} className="grid" style={{gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))'}}><label>Name<input name="name" required/></label><label>Key<input name="key" placeholder="ai_webinar_invite" required/></label><label>Channel<select name="channel"><option>EMAIL</option><option>WHATSAPP</option></select></label><label>Email subject<input name="subject" placeholder="Hi {{name}}, join our webinar"/></label><label>WhatsApp approved template<input name="providerTemplateName" placeholder="academy_webinar_invite"/></label><label style={{gridColumn:'1/-1'}}>Text / preview<textarea name="bodyText" rows={5} required placeholder="Hi {{name}}, explore {{program}}..."/></label><label style={{gridColumn:'1/-1'}}>Optional email HTML<textarea name="bodyHtml" rows={5}/></label><button className="btn primary">Create template</button></form><div style={{marginTop:16}}>{templates.map(t=><span key={t.id} className="pill" style={{marginRight:8}}>{t.channel} · {t.name}</span>)}</div></section>
  <section className="card"><h2>Create campaign</h2><form onSubmit={createCampaign} className="grid" style={{gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))'}}><label>Name<input name="name" required/></label><label>Template<select name="templateId" required>{templates.map(t=><option key={t.id} value={t.id}>{t.channel} · {t.name}</option>)}</select></label><label>Lead statuses<input name="statuses" placeholder="NEW,CONTACTED,QUALIFIED"/></label><label>Programs<input name="programSlugs" placeholder="ai-engineering,full-stack"/></label><label>Max recipients<input name="limit" type="number" defaultValue="500" min="1" max="5000"/></label><button className="btn primary">Create campaign</button></form></section>
  <section className="card"><h2>Campaigns</h2><div className="grid">{campaigns.map(c=><div className="card" key={c.id}><strong>{c.name}</strong><p className="muted">{c.channel} · {c.template.name} · {c.status} · {c._count.recipients} recipients</p>{c.stats&&<p>{JSON.stringify(c.stats)}</p>}<button className="btn" disabled={['SENDING','COMPLETED','CANCELLED'].includes(c.status)} onClick={()=>send(c.id)}>Send now</button></div>)}</div></section>
  {msg&&<div className="card"><strong>{msg}</strong></div>}
 </div>
}
