import config from '@payload-config'
import { getPayload } from 'payload'
import Link from 'next/link'

export const revalidate = 300

export default async function BlogIndex() {
  if (process.env.UX_CAPTURE_MODE === '1') return <main className="insights-page"><section className="insights-hero"><div><span>RESOURCES · INSIGHTS · PRACTICE</span><h1>Ideas that help you build, decide and grow.</h1><p>Deep, practical writing from engineers, faculty, mentors and operators—connected directly to courses, labs and live sessions.</p><div><button>Explore latest insights</button><button>Browse learning guides</button></div></div><article><small>FEATURED GUIDE · 12 MIN READ</small><h2>From AI demo to reliable production system</h2><p>A field guide to evaluation, guardrails, observability and the decisions that turn prototypes into useful systems.</p><Link href="/blog/building-reliable-ai-systems">Read the field guide →</Link></article></section><section className="insights-shell"><div className="insight-topbar"><div><button className="active">All</button><button>AI & agents</button><button>Full-stack</button><button>Data</button><button>Cybersecurity</button><button>Venture building</button></div><input placeholder="Search articles, guides and tutorials…"/></div><div className="insight-layout"><main><h2>Latest insights</h2><div className="insight-grid">{[['AI & AGENTIC SYSTEMS','Designing evaluations before deployment','A practical method for choosing signals, datasets and review loops.','10 min'],['FULL-STACK','The anatomy of a production-ready web project','Structure, testing, accessibility and deployment without needless complexity.','8 min'],['DATA & ANALYTICS','What makes a dashboard trustworthy?','Move from attractive charts to clear definitions and decision-ready evidence.','7 min'],['VENTURE BUILDER','Customer interviews before MVP code','How to learn faster without turning every conversation into a sales pitch.','9 min'],['CYBERSECURITY','Threat modelling for learning projects','A lightweight workflow for identifying assets, trust boundaries and abuse cases.','11 min'],['CAREERS','Build a portfolio that explains your decisions','Show the problem, constraints, trade-offs and evidence—not just a screenshot.','6 min']].map((x,i)=><article key={x[1]}><div className={`insight-art a${i}`}><span>{x[0]}</span><i>{['◎','</>','↗','◇','⌁','▣'][i]}</i></div><section><small>{x[0]} · {x[3]}</small><h3>{x[1]}</h3><p>{x[2]}</p><Link href={i===0?'/blog/building-reliable-ai-systems':'#'}>Read article →</Link></section></article>)}</div></main><aside><h2>Learning guides</h2>{['JavaScript foundations reference','RAG system design checklist','Data storytelling workbook','Venture validation interview guide'].map((x,i)=><article key={x}><i>{String(i+1).padStart(2,'0')}</i><div><b>{x}</b><span>Downloadable guide</span></div><button>↓</button></article>)}<div className="insight-newsletter"><span>WEEKLY LEARNING NOTE</span><h3>One useful idea. No noise.</h3><p>Get new guides, labs and webinar notes.</p><input placeholder="Email address"/><button>Subscribe →</button></div></aside></div></section></main>
  const payload = await getPayload({ config })
  const posts = await payload.find({ collection: 'posts', where: { _status: { equals: 'published' } }, sort: '-publishedAt', depth: 1, limit: 24, overrideAccess: false })
  return <main><section className="hero compact"><div className="shell"><span className="pill">INSIGHTS • TECHNOLOGY • LEARNING</span><h1>SamkhyaAcademy Insights</h1><p>Practical perspectives from our internal faculty and subject-matter experts across AI, engineering, enterprise technology and deep tech.</p></div></section><section><div className="shell"><div className="grid">{posts.docs.map((post:any)=><article className="card" key={post.id}>{post.heroImage && typeof post.heroImage==='object' && <img className="card-image" src={post.heroImage.url} alt={post.heroImage.alt || post.title}/>}<span className="pill">{post.category}</span><h2>{post.title}</h2><p className="muted">{post.excerpt}</p><Link className="btn" href={`/blog/${post.slug}`}>Read article</Link></article>)}</div>{posts.docs.length===0&&<div className="card"><h3>No published articles yet</h3><p className="muted">Internal editors can create and publish posts from Content Studio.</p><Link className="btn" href="/content-studio">Open Content Studio</Link></div>}</div></section></main>
}
