import { chromium, type BrowserContext } from "@playwright/test";
import { mkdir, readdir, unlink, writeFile } from "node:fs/promises";
import path from "node:path";

type Role = "public" | "learner" | "admin" | "org" | "mentor" | "cms";
type Screen = {
  n: number;
  name: string;
  area: string;
  route: string;
  role: Role;
  links: string;
  status: "implemented" | "context-dependent" | "gap-shell";
};
const screens: Screen[] = [
  {
    n: 1,
    name: "Academy Homepage",
    area: "Public",
    route: "/",
    role: "public",
    links: "Courses / Learning Paths / Programs / Webinars / Organizations",
    status: "implemented",
  },
  {
    n: 2,
    name: "Course Catalog",
    area: "Public",
    route: "/public-preview/2",
    role: "public",
    links: "Program detail / filters",
    status: "implemented",
  },
  {
    n: 3,
    name: "Learning Paths",
    area: "Public",
    route: "/public-preview/3",
    role: "public",
    links: "Path detail",
    status: "implemented",
  },
  {
    n: 4,
    name: "FDE Engineering Program",
    area: "Program",
    route: "/public-preview/4",
    role: "public",
    links: "Brochure / enrollment",
    status: "implemented",
  },
  {
    n: 5,
    name: "Applied ML Engineer Program",
    area: "Program",
    route: "/public-preview/5",
    role: "public",
    links: "Preview / brochure / enrollment",
    status: "implemented",
  },
  {
    n: 6,
    name: "Full Stack Program",
    area: "Program",
    route: "/public-preview/6",
    role: "public",
    links: "Preview / brochure / enrollment",
    status: "implemented",
  },
  {
    n: 7,
    name: "Video Lesson Experience",
    area: "Learner",
    route: "/course-experience/video?preview=1",
    role: "learner",
    links: "Next lesson / resources / progress",
    status: "implemented",
  },
  {
    n: 8,
    name: "Practice / Quiz Experience",
    area: "Learner",
    route: "/learning-studio/practice?preview=1",
    role: "learner",
    links: "Submit / next / result",
    status: "implemented",
  },
  {
    n: 9,
    name: "Entrepreneurship Landing",
    area: "Venture",
    route: "/entrepreneurship",
    role: "public",
    links: "Idea submission / apply",
    status: "implemented",
  },
  {
    n: 10,
    name: "Idea Submission & Intake",
    area: "Venture",
    route: "/venture-builder/experience/intake?preview=1",
    role: "public",
    links: "Save draft / continue / submit",
    status: "implemented",
  },
  {
    n: 11,
    name: "FDE Leadership Program",
    area: "Program",
    route: "/public-preview/11",
    role: "public",
    links: "Brochure / webinar / apply",
    status: "implemented",
  },
  {
    n: 12,
    name: "Space Tech Program",
    area: "Program",
    route: "/public-preview/12",
    role: "public",
    links: "Brochure / apply",
    status: "implemented",
  },
  {
    n: 13,
    name: "Data Analytics Program",
    area: "Program",
    route: "/public-preview/13",
    role: "public",
    links: "Preview / enrollment",
    status: "implemented",
  },
  {
    n: 14,
    name: "Cybersecurity Program",
    area: "Program",
    route: "/public-preview/14",
    role: "public",
    links: "Enrollment",
    status: "implemented",
  },
  {
    n: 15,
    name: "Free Course Access State",
    area: "Commercial",
    route: "/public-preview/15",
    role: "public",
    links: "Start free course",
    status: "implemented",
  },
  {
    n: 16,
    name: "Freemium Preview State",
    area: "Commercial",
    route: "/public-preview/16",
    role: "public",
    links: "Unlock / upgrade",
    status: "implemented",
  },
  {
    n: 17,
    name: "Paid Course Pricing State",
    area: "Commercial",
    route: "/public-preview/17",
    role: "public",
    links: "Buy / offer",
    status: "implemented",
  },
  {
    n: 18,
    name: "Learner Dashboard",
    area: "Learner",
    route: "/experience-preview/18",
    role: "public",
    links: "Continue learning / certificates",
    status: "implemented",
  },
  {
    n: 19,
    name: "Course Progress Dashboard",
    area: "Learner",
    route: "/experience-preview/19",
    role: "public",
    links: "Course / lesson / exam detail",
    status: "implemented",
  },
  {
    n: 20,
    name: "Lesson Resources / Comments / Notes",
    area: "Learner",
    route: "/experience-preview/20",
    role: "public",
    links: "Resource / post / next",
    status: "implemented",
  },
  {
    n: 21,
    name: "Exam Start / Instructions",
    area: "Exam",
    route: "/experience-preview/21",
    role: "public",
    links: "Start attempt",
    status: "implemented",
  },
  {
    n: 22,
    name: "Exam Question Taking",
    area: "Exam",
    route: "/experience-preview/22",
    role: "public",
    links: "Navigate / submit",
    status: "implemented",
  },
  {
    n: 23,
    name: "Exam Result",
    area: "Exam",
    route: "/experience-preview/23",
    role: "public",
    links: "Review / retry / certificate",
    status: "implemented",
  },
  {
    n: 24,
    name: "Certificate + Verification",
    area: "Certificate",
    route: "/experience-preview/24",
    role: "public",
    links: "Download / verify / share",
    status: "implemented",
  },
  {
    n: 25,
    name: "Venture Stage Workflow",
    area: "Venture",
    route: "/venture-builder",
    role: "learner",
    links: "Tasks / artifacts / review",
    status: "implemented",
  },
  {
    n: 26,
    name: "Venture Artifacts & Launch Readiness",
    area: "Venture",
    route: "/venture-builder/workspaces/seed-venture-workspace/artifacts",
    role: "learner",
    links: "Upload / submit for review",
    status: "implemented",
  },
  {
    n: 27,
    name: "Mentor Review & Feedback",
    area: "Venture",
    route: "/platform-admin/venture-builder/seed-venture-workspace/IDEA",
    role: "mentor",
    links: "Respond / resubmit",
    status: "implemented",
  },
  {
    n: 28,
    name: "Venture Milestones / Traction",
    area: "Venture",
    route: "/venture-builder/workspaces/seed-venture-workspace/workflow",
    role: "learner",
    links: "Metrics / next milestone",
    status: "implemented",
  },
  {
    n: 29,
    name: "Venture Cohort Admin Dashboard",
    area: "Mentor/Admin",
    route: "/experience-preview/29",
    role: "public",
    links: "Review queue / cohort",
    status: "implemented",
  },
  {
    n: 30,
    name: "Platform Admin Dashboard",
    area: "Admin",
    route: "/experience-preview/30",
    role: "public",
    links: "Users / courses / organizations / CRM",
    status: "implemented",
  },
  {
    n: 31,
    name: "CMS Course Management List",
    area: "CMS",
    route: "/experience-preview/31",
    role: "public",
    links: "Create / edit / publish",
    status: "implemented",
  },
  {
    n: 32,
    name: "Create/Edit Course",
    area: "CMS",
    route: "/experience-preview/32",
    role: "public",
    links: "Commercial / content setup",
    status: "implemented",
  },
  {
    n: 33,
    name: "Course Pricing Category Admin",
    area: "CMS",
    route: "/experience-preview/33",
    role: "public",
    links: "Free / Freemium / Pricing",
    status: "implemented",
  },
  {
    n: 34,
    name: "Content Type Admin",
    area: "CMS",
    route: "/experience-preview/34",
    role: "public",
    links: "Online / Hybrid / Offline",
    status: "implemented",
  },
  {
    n: 35,
    name: "Module & Lesson Builder",
    area: "CMS",
    route: "/experience-preview/35",
    role: "public",
    links: "Add / edit / reorder / publish",
    status: "implemented",
  },
  {
    n: 36,
    name: "Exam & Question Bank Management",
    area: "CMS",
    route: "/experience-preview/36",
    role: "public",
    links: "Question / exam CRUD",
    status: "implemented",
  },
  {
    n: 37,
    name: "Blog CMS Editor",
    area: "CMS",
    route: "/experience-preview/37",
    role: "public",
    links: "Draft / preview / publish",
    status: "implemented",
  },
  {
    n: 38,
    name: "Webinar CMS Management",
    area: "CMS",
    route: "/experience-preview/38",
    role: "public",
    links: "Create / schedule / registrations",
    status: "implemented",
  },
  {
    n: 39,
    name: "Faculty & Media Library",
    area: "CMS",
    route: "/experience-preview/39",
    role: "public",
    links: "Upload / manage / reuse",
    status: "implemented",
  },
  {
    n: 40,
    name: "Organization Dashboard",
    area: "Organization",
    route: "/experience-preview/40",
    role: "public",
    links: "Members / learning / reports",
    status: "implemented",
  },
  {
    n: 41,
    name: "Organization Learner Onboarding",
    area: "Organization",
    route: "/experience-preview/41",
    role: "public",
    links: "Invite / bulk onboarding",
    status: "implemented",
  },
  {
    n: 42,
    name: "Organization Assignments & Progress",
    area: "Organization",
    route: "/experience-preview/42",
    role: "public",
    links: "Assign / report",
    status: "implemented",
  },
  {
    n: 43,
    name: "Brochure Lead Gate",
    area: "Lead",
    route: "/experience-preview/43",
    role: "public",
    links: "Submit details / download",
    status: "implemented",
  },
  {
    n: 44,
    name: "Webinar Registration",
    area: "Lead",
    route: "/experience-preview/44",
    role: "public",
    links: "Register / confirmation",
    status: "context-dependent",
  },
  {
    n: 45,
    name: "CRM Leads Dashboard",
    area: "Operations",
    route: "/experience-preview/45",
    role: "public",
    links: "Lead detail / follow-up",
    status: "implemented",
  },
  {
    n: 46,
    name: "CRM Lead Detail & Follow-up",
    area: "Operations",
    route: "/experience-preview/46",
    role: "public",
    links: "Activity / offer / message",
    status: "context-dependent",
  },
  {
    n: 47,
    name: "Campaigns Dashboard",
    area: "Operations",
    route: "/experience-preview/47",
    role: "public",
    links: "Email / WhatsApp campaign",
    status: "implemented",
  },
  {
    n: 48,
    name: "WhatsApp Operation Screen",
    area: "Operations",
    route: "/experience-preview/48",
    role: "public",
    links: "Template / recipient / send",
    status: "implemented",
  },
  {
    n: 49,
    name: "Email Campaign Screen",
    area: "Operations",
    route: "/experience-preview/49",
    role: "public",
    links: "Template / segment / schedule",
    status: "implemented",
  },
  {
    n: 50,
    name: "Private Discount Offer",
    area: "Offer",
    route: "/experience-preview/50",
    role: "public",
    links: "Proceed to payment",
    status: "implemented",
  },
  {
    n: 51,
    name: "Razorpay Payment Handoff",
    area: "Payment",
    route: "/experience-preview/51",
    role: "public",
    links: "Pay / cancel",
    status: "implemented",
  },
  {
    n: 52,
    name: "Payment Success + Enrollment",
    area: "Payment",
    route: "/experience-preview/52",
    role: "public",
    links: "Start learning",
    status: "implemented",
  },
  {
    n: 53,
    name: "Text Lesson Reader",
    area: "Learner",
    route: "/learning-studio/text-lesson?preview=1",
    role: "learner",
    links: "Code example / practice / notes / discussion",
    status: "implemented",
  },
  {
    n: 54,
    name: "Interactive Browser Code Lab",
    area: "Learner",
    route: "/learning-studio/code-lab?preview=1",
    role: "learner",
    links: "Edit / run / live preview / download",
    status: "implemented",
  },
  {
    n: 55,
    name: "Practice Checkpoint",
    area: "Learner",
    route: "/learning-studio/practice?preview=1",
    role: "learner",
    links: "Requirements / hints / check solution",
    status: "implemented",
  },
  {
    n: 56,
    name: "Code Snippet Library",
    area: "Learner",
    route: "/learning-studio/snippets?preview=1",
    role: "learner",
    links: "Copy / export / open in lab",
    status: "implemented",
  },
  {
    n: 57,
    name: "Downloadable Project Library",
    area: "Learner",
    route: "/learning-studio/project-library?preview=1",
    role: "learner",
    links: "Filter / preview / project package",
    status: "implemented",
  },
  {
    n: 58,
    name: "Project Package Detail",
    area: "Learner",
    route: "/learning-studio/project-detail?preview=1",
    role: "learner",
    links: "GIF preview / file tree / ZIP / milestones",
    status: "implemented",
  },
  {
    n: 59,
    name: "Insights and Blog Index",
    area: "Public",
    route: "/blog",
    role: "public",
    links: "Search / categories / article / guides",
    status: "implemented",
  },
  {
    n: 60,
    name: "Rich Blog Article",
    area: "Public",
    route: "/blog/building-reliable-ai-systems",
    role: "public",
    links: "Sections / code / checklist / related program",
    status: "implemented",
  },
  {
    n: 61,
    name: "Lesson Experience Selector",
    area: "CMS",
    route: "/platform-admin/content?view=lessonTypes&preview=1",
    role: "admin",
    links: "Video / text / lab / practice / project / quiz",
    status: "implemented",
  },
  {
    n: 62,
    name: "Text Lesson Authoring",
    area: "CMS",
    route: "/platform-admin/content?view=articleEditor&preview=1",
    role: "admin",
    links: "Rich blocks / code / callout / preview",
    status: "implemented",
  },
  {
    n: 63,
    name: "Code Lab Authoring",
    area: "CMS",
    route: "/platform-admin/content?view=labEditor&preview=1",
    role: "admin",
    links: "Starter files / hints / checks / sandbox policy",
    status: "implemented",
  },
  {
    n: 64,
    name: "Project Package Authoring",
    area: "CMS",
    route: "/platform-admin/content?view=projectPackage&preview=1",
    role: "admin",
    links: "ZIP / brief / GIF / file tree / rubric",
    status: "implemented",
  },
  {
    n: 65,
    name: "Code Lab Hint Open",
    area: "Learner Continuation",
    route: "/learning-studio/code-lab-hint?preview=1",
    role: "learner",
    links: "Apply hint / return to editor",
    status: "implemented",
  },
  {
    n: 66,
    name: "Practice Checks Failed",
    area: "Learner Continuation",
    route: "/learning-studio/practice-failed?preview=1",
    role: "learner",
    links: "Locate errors / return to editor",
    status: "implemented",
  },
  {
    n: 67,
    name: "Practice Completion Success",
    area: "Learner Continuation",
    route: "/learning-studio/practice-passed?preview=1",
    role: "learner",
    links: "Review / continue",
    status: "implemented",
  },
  {
    n: 68,
    name: "Mobile Code Preview",
    area: "Learner Continuation",
    route: "/learning-studio/code-lab-mobile?preview=1",
    role: "learner",
    links: "Switch device / full-screen preview",
    status: "implemented",
  },
  {
    n: 69,
    name: "Lesson Notes Drawer",
    area: "Learner Continuation",
    route: "/learning-studio/code-lab-notes?preview=1",
    role: "learner",
    links: "Edit / link to code / save",
    status: "implemented",
  },
  {
    n: 70,
    name: "Lesson Discussion Drawer",
    area: "Learner Continuation",
    route: "/learning-studio/code-lab-discussion?preview=1",
    role: "learner",
    links: "Post / reply / mark helpful",
    status: "implemented",
  },
  {
    n: 71,
    name: "Resource Preview Drawer",
    area: "Learner Continuation",
    route: "/learning-studio/code-lab-resource?preview=1",
    role: "learner",
    links: "Preview / open / download",
    status: "implemented",
  },
  {
    n: 72,
    name: "Practice Correction State",
    area: "Learner Continuation",
    route: "/learning-studio/practice-hint?preview=1",
    role: "learner",
    links: "Use progressive hint / retry",
    status: "implemented",
  },
  {
    n: 73,
    name: "Idea Intake Validation",
    area: "Venture Continuation",
    route: "/venture-builder/experience/intake-error?preview=1",
    role: "public",
    links: "Correct fields / continue",
    status: "implemented",
  },
  {
    n: 74,
    name: "Idea Submission Receipt",
    area: "Venture Continuation",
    route: "/venture-builder/experience/submitted?preview=1",
    role: "public",
    links: "Track submission / prepare",
    status: "implemented",
  },
  {
    n: 75,
    name: "Active Venture Stage",
    area: "Venture Continuation",
    route: "/venture-builder/experience/workflow?preview=1",
    role: "learner",
    links: "Tasks / evidence / submit",
    status: "implemented",
  },
  {
    n: 76,
    name: "Artifact Library and Upload",
    area: "Venture Continuation",
    route: "/venture-builder/experience/artifact?preview=1",
    role: "learner",
    links: "Upload / version / submit",
    status: "implemented",
  },
  {
    n: 77,
    name: "Mentor Review Pending",
    area: "Venture Continuation",
    route: "/venture-builder/experience/review-pending?preview=1",
    role: "learner",
    links: "Track review / view package",
    status: "implemented",
  },
  {
    n: 78,
    name: "Mentor Changes Requested",
    area: "Venture Continuation",
    route: "/venture-builder/experience/changes?preview=1",
    role: "learner",
    links: "Read rubric / revise",
    status: "implemented",
  },
  {
    n: 79,
    name: "Venture Stage Resubmission",
    area: "Venture Continuation",
    route: "/venture-builder/experience/resubmit?preview=1",
    role: "learner",
    links: "Resolve / attach / resubmit",
    status: "implemented",
  },
  {
    n: 80,
    name: "Venture Stage Unlocked",
    area: "Venture Continuation",
    route: "/venture-builder/experience/unlocked?preview=1",
    role: "learner",
    links: "Review history / next stage",
    status: "implemented",
  },
  {
    n: 81,
    name: "Venture Workspace Overview",
    area: "Venture Golden Master",
    route: "/venture-builder/experience/workspace?preview=1",
    role: "learner",
    links: "Tasks / artifacts / mentor / stage resources",
    status: "implemented",
  },
  {
    n: 82,
    name: "Unified Video Course Lesson",
    area: "Course Experience",
    route: "/course-experience/video?preview=1",
    role: "learner",
    links: "Modules / player / resources / discussion",
    status: "implemented",
  },
  {
    n: 83,
    name: "Unified Text Course Lesson",
    area: "Course Experience",
    route: "/course-experience/text?preview=1",
    role: "learner",
    links: "Reader / notes / resources / discussion",
    status: "implemented",
  },
  {
    n: 84,
    name: "Unified Mixed Example Lesson",
    area: "Course Experience",
    route: "/course-experience/example?preview=1",
    role: "learner",
    links: "Code / rendered result / practice",
    status: "implemented",
  },
  {
    n: 85,
    name: "Programming Foundations Catalog",
    area: "Free Acquisition",
    route: "/programming/catalog?preview=1",
    role: "public",
    links: "C / C++ / DSA",
    status: "implemented",
  },
  {
    n: 86,
    name: "Free C Course Detail",
    area: "Free Acquisition",
    route: "/programming/c-course?preview=1",
    role: "public",
    links: "Enroll free / curriculum",
    status: "implemented",
  },
  {
    n: 87,
    name: "Free C Text Lesson",
    area: "Free Learning",
    route: "/course-experience/text?track=c&preview=1",
    role: "learner",
    links: "Pointers / examples / practice",
    status: "implemented",
  },
  {
    n: 88,
    name: "Free C Plus Plus Course Detail",
    area: "Free Acquisition",
    route: "/programming/cpp-course?preview=1",
    role: "public",
    links: "Enroll free / curriculum",
    status: "implemented",
  },
  {
    n: 89,
    name: "Free C++ Video Lesson",
    area: "Free Learning",
    route: "/course-experience/video?track=cpp&preview=1",
    role: "learner",
    links: "Classes / notes / discussion",
    status: "implemented",
  },
  {
    n: 90,
    name: "Paid DSA Course Detail",
    area: "Paid Learning",
    route: "/programming/dsa-course?preview=1",
    role: "public",
    links: "Preview / enroll / curriculum",
    status: "implemented",
  },
  {
    n: 91,
    name: "DSA Graph Traversal Simulation",
    area: "Interactive Simulation",
    route: "/programming/dsa-graph?preview=1",
    role: "learner",
    links: "Step / autoplay / inspect state",
    status: "implemented",
  },
  {
    n: 92,
    name: "DSA Linked List Simulation",
    area: "Interactive Simulation",
    route: "/programming/dsa-list?preview=1",
    role: "learner",
    links: "Insert / remove / inspect pointers",
    status: "implemented",
  },
  {
    n: 93,
    name: "Simulation Lesson Authoring",
    area: "CMS",
    route: "/platform-admin/content?view=lessonTypes&preview=1",
    role: "admin",
    links: "Select SVG simulation / configure",
    status: "implemented",
  },
  {
    n: 94,
    name: "Protected Setting Approval Queue",
    area: "Super Admin",
    route: "/platform-admin/content?view=changeRequests&preview=1",
    role: "admin",
    links: "Compare / approve / reject",
    status: "implemented",
  },
  {
    n: 95,
    name: "Immutable Publishing Queue",
    area: "Super Admin",
    route: "/platform-admin/content?view=publishing&preview=1",
    role: "admin",
    links: "Validate / publish / reject",
    status: "implemented",
  },
];

const base = process.env.SCREEN_BASE_URL || "http://localhost:3000";
const out = path.join(process.cwd(), "docs", "ux", "generated");
await mkdir(out, { recursive: true });
const fromArg = process.argv.find((arg) => arg.startsWith("--from="));
const fromScreen = fromArg ? Number(fromArg.split("=")[1]) : 1;
const toArg = process.argv.find((arg) => arg.startsWith("--to="));
const toScreen = toArg ? Number(toArg.split("=")[1]) : screens.length;
const screensArg = process.argv.find((arg) => arg.startsWith("--screens="));
const requestedScreens = screensArg
  ? new Set(
      screensArg
        .split("=")[1]
        .split(",")
        .map(Number)
        .filter(Number.isFinite),
    )
  : null;
const captureScreens = screens.filter((screen) =>
  requestedScreens
    ? requestedScreens.has(screen.n)
    : screen.n >= fromScreen && screen.n <= toScreen,
);
const browser = await chromium.launch({ headless: true });
async function context(role: Role) {
  const c = await browser.newContext({
    viewport: { width: 1440, height: 1000 },
    deviceScaleFactor: 1,
  });
  if (role !== "public" && role !== "cms") {
    const email =
      role === "admin"
        ? "admin@samkhyaacademy.local"
        : role === "org"
          ? "orgadmin@samkhyaacademy.local"
          : role === "mentor"
            ? "mentor@samkhyaacademy.local"
            : "learner@samkhyaacademy.local";
    await c.request.post(`${base}/api/auth/login`, {
      data: { email, password: "ChangeMe-Immediately-123!" },
    });
  }
  if (role === "cms") {
    const p = await c.newPage();
    await p.goto(`${base}/content-studio/login`, { waitUntil: "networkidle" });
    await p.getByLabel("Email *").fill("content.admin@samkhyaacademy.local");
    await p.getByLabel("Password").fill("ChangeMe-Immediately-123!");
    await p.getByRole("button", { name: "Login" }).click();
    await p.waitForURL("**/content-studio");
    await p.close();
  }
  return c;
}
const contexts = new Map<Role, BrowserContext>();
for (const s of captureScreens) {
  let c = contexts.get(s.role);
  if (!c) {
    c = await context(s.role);
    contexts.set(s.role, c);
  }
  const p = await c.newPage();
  await p
    .goto(`${base}${s.route}`, { waitUntil: "networkidle", timeout: 45000 })
    .catch(() => {});
  if (s.n === 43) {
    const button = p.getByRole("button", { name: /brochure/i }).first();
    if (await button.isVisible().catch(() => false)) await button.click();
  }
  const screenPrefix = `${String(s.n).padStart(2, "0")}-`;
  const priorCaptures = (await readdir(out)).filter(
    (file) => file.startsWith(screenPrefix) && file.endsWith(".png"),
  );
  await Promise.all(
    priorCaptures.map((file) => unlink(path.join(out, file))),
  );
  await p.screenshot({
    path: path.join(
      out,
      `${String(s.n).padStart(2, "0")}-${s.name
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-|-$/g, "")}.png`,
    ),
    fullPage: true,
  });
  await p.close();
  console.log(`${s.n}/${screens.length} ${s.name}`);
}
for (const c of contexts.values()) await c.close();
await browser.close();

const md = [
  "# Expanded 95-Screen Customer Prototype Inventory",
  "",
  "Screen 13 (standalone SAP Enterprise Consulting) from the original BRD is retired. Original screens 14–53 are renumbered 13–52. Screens 53–64 add multi-format learning and authoring. Screens 65–72 are learner continuation states. Screens 73–81 complete the Venture Builder loop and daily workspace. Screens 82–95 add the shared course shell, free C/C++ journeys, paid DSA simulations, and two-person administration. Status reflects the implemented repository at verification time.",
  "",
  "| # | Screen | Area | Route / context | Status | Screenshot |",
  "|---:|---|---|---|---|---|",
  ...screens.map(
    (s) =>
      `| ${s.n} | ${s.name} | ${s.area} | \`${s.route}\` (${s.role}) | ${s.status} | [PNG](./generated/${String(s.n).padStart(2, "0")}-${s.name
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-|-$/g, "")}.png) |`,
  ),
  "",
  "Status meanings: `implemented` is directly usable; `context-dependent` needs seeded transactional context or provider return state; `gap-shell` has the surrounding product route but still needs its dedicated interaction surface.",
];
await writeFile(
  path.join(process.cwd(), "docs", "ux", "SCREEN_INVENTORY.md"),
  md.join("\n"),
);
const csv = [
  "screen,name,area,route,role,status,primary_links,screenshot",
  ...screens.map((s) =>
    [
      s.n,
      s.name,
      s.area,
      s.route,
      s.role,
      s.status,
      s.links,
      `generated/${String(s.n).padStart(2, "0")}-${s.name
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-|-$/g, "")}.png`,
    ]
      .map((v) => `"${String(v).replaceAll('"', '""')}"`)
      .join(","),
  ),
];
await writeFile(
  path.join(process.cwd(), "docs", "ux", "MARVEL_PROTOTYPE_MAP.csv"),
  csv.join("\n"),
);
const mappedDestinations: Record<number, string> = {
  1: "2 / 3 / 9 / 44",
  2: "4 / 5 / 6 / 11–14",
  7: "20 / 21 / 53 / 54",
  9: "10",
  10: "25",
  15: "18",
  16: "51",
  17: "51",
  18: "19 / 21 / 24 / 25",
  25: "26 / 28",
  26: "27",
  27: "26 / 28",
  30: "31 / 40 / 45",
  31: "32 / 35 / 36 / 37–39 / 61",
  40: "41 / 42",
  43: "4",
  45: "46 / 47",
  46: "47 / 50",
  47: "48 / 49",
  50: "51",
  51: "52",
  52: "7 / 53",
  53: "54 / 55 / 56",
  54: "55 / 56 / 57",
  55: "56 / 57",
  56: "54 / 57",
  57: "58",
  58: "54 / 57",
  59: "60",
  60: "4 / 53 / 54 / 59",
  61: "62 / 63 / 64",
  62: "53 / 61",
  63: "54 / 61",
  64: "58 / 61",
  65: "54 / 66",
  66: "65 / 67",
  67: "56 / 57",
  68: "54 / 69",
  69: "54 / 70",
  70: "54 / 71",
  71: "54 / 55",
  72: "55 / 66",
  73: "74",
  74: "75",
  75: "76 / 77",
  76: "77",
  77: "78 / 80",
  78: "79",
  79: "77 / 80",
  80: "75",
  81: "75 / 76 / 77",
  82: "83 / 84",
  83: "84",
  84: "82 / 85",
  85: "86 / 88 / 90",
  86: "87",
  87: "88 / 90",
  88: "89",
  89: "90",
  90: "91 / 92",
  91: "92 / 93",
  92: "91 / 93",
  93: "94",
  94: "95",
  95: "90",
};
const marvel = [
  "# Marvel Prototype Map",
  "",
  "Upload the PNGs in numeric filename order. Create the hotspots below as deliberate journey branches; do not connect every screen as a simple slideshow. Screen 13 in the old map is intentionally omitted; every later old screen number is reduced by one.",
  "",
  "| Screen | Hotspot intent | Destination screen(s) |",
  "|---:|---|---|",
  ...screens.map(
    (s, i) =>
      `| ${s.n} — ${s.name} | ${s.links} | ${mappedDestinations[s.n] ?? (i < screens.length - 1 ? `${screens[i + 1].n} — ${screens[i + 1].name}` : "1 — Academy Homepage")} |`,
  ),
  "",
  "## Required connected journeys",
  "",
  "- Multi-format learner: 18 → 53 → 54 → 65/68/69/70/71 → 55 → 66 → 72 → 67 → 56 → 57 → 58.",
  "- Editorial acquisition: 1 → 59 → 60 → 4/53/54.",
  "- Author-to-learner preview: 31 → 61 → 62/63/64 → 53/54/58.",
  "- Commercial: 15 → 18; 16/17/50 → 51 → 52.",
  "- Venture Builder: 9 → 10 → 25 → 26 → 27 → 28.",
  "- Venture Builder continuation: 73 → 74 → 75 → 76 → 77 → 78 → 79 → 77 → 80.",
  "- Venture daily workspace: 81 → 75/76/77.",
  "- Unified course experience: 82 → 83 → 84.",
  "- Free-to-paid programming: 85 → 86 → 87 → 88 → 89 → 90 → 91/92.",
  "- Course governance: 93 → 94 → 95.",
  "- Organization: 40 → 41 → 42.",
  "- Operations: 45 → 46 → 47 → 48/49.",
];
await writeFile(
  path.join(process.cwd(), "docs", "ux", "MARVEL_PROTOTYPE_MAP.md"),
  marvel.join("\n"),
);
