import {mkdir,readFile,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {chromium} from 'playwright';
import {courseCatalog} from '../../packages/catalog/src/index.ts';
import {curriculum,lessonFile} from './curriculum.mjs';
import {marketing,courseScreens,brochureName} from './marketing.mjs';
import {esc,icon} from './render.mjs';
const out=path.resolve('output/UX_REVIEW_ASTRA_2026_09_05'),dir=path.join(out,'brochures');
await mkdir(path.join(dir,'html'),{recursive:true});
const base='https://gajapathiks.github.io/SamkhyaAcademy';
const css=await readFile('scripts/ux-rebuild/assets/brochure.css','utf8');
await writeFile(path.join(dir,'brochure.css'),css+`
.syllabus{display:grid;gap:4mm;flex:1;align-content:start}.syllabus[data-count="4"]{grid-template-columns:1fr 1fr}.syllabus .module{padding:4mm}.syllabus h3{font-size:12pt}.syllabus .module>p{font-size:9.5pt;margin:2mm 0}.syllabus ol{padding:0;margin:3mm 0;list-style:none}.syllabus li{font-size:9.3pt;line-height:1.5;margin:2.5mm 0;display:grid;grid-template-columns:8mm 1fr;gap:2mm}.syllabus li>b{color:#5238de}.syllabus li strong{display:block;color:#16214a}.syllabus .evidence-line{border-top:1px solid #dde2ee;padding-top:2mm;font-size:9pt}.syllabus[data-count="4"] li{font-size:8.7pt;margin:2mm 0}.syllabus[data-count="4"] .module>p{font-size:8.8pt}.syllabus[data-count="4"] h3{font-size:10.5pt}.syllabus[data-count="4"] .module{padding:3mm}.learning-process{display:grid;grid-template-columns:repeat(3,1fr);gap:3mm}.learning-process>div{border:1px solid #dde2ef;padding:4mm;border-radius:8px}.learning-process h3{font-size:10pt;margin:2mm 0}.learning-process p{font-size:9pt}.sheet:nth-child(4){gap:5mm}.sheet:nth-child(4) .card{padding:4mm}.module-context{color:#475773}.sheet .foot{font-size:7pt}.syllabus[data-count="3"] li{margin:1.5mm 0;font-size:8.9pt}.syllabus[data-count="3"] .module{padding:3mm}.syllabus[data-count="3"] .module>p{font-size:8.9pt}.syllabus[data-count="3"] h3{font-size:10.5pt}
`);
await writeFile(path.join(dir,'brochure.css'),'\n.syllabus[data-count="3"]{grid-template-columns:1fr 1fr}.syllabus[data-count="3"] .module:last-child{grid-column:1/-1}',{flag:'a'});
const browser=await chromium.launch(),page=await browser.newPage(),results=[];
for(const c of courseCatalog){
 const plan=curriculum(c),m=marketing[c.slug],courseUrl=base+'/pages/'+String(courseScreens[c.slug]).padStart(3,'0')+'.html',entry=base+'/pages/'+lessonFile(c.slug);
 const delivery=({SELF_PACED:'Self-paced online',HYBRID:'Hybrid learning',OFFLINE:'In-person learning',COHORT:'Cohort-based learning',LIVE_ONLINE:'Live online'})[c.deliveryMode];
 const mast='<div class="mast"><div class="brand">Samkhya<em>Academy</em></div><span>COURSE GUIDE · 2026</span></div>';
 const wrap=(n:number,content:string,cover=false)=>`<section class="sheet ${cover?['ai-leadership','entrepreneurship'].includes(c.slug)?'cover warm':'cover':''}" style="--accent:${m.accent}">${mast}${content}<footer class="foot"><span>${esc(c.title)} · Curriculum ${plan.version}</span><span>0${n} / 06</span></footer></section>`;
 const list=(xs:string[])=>'<ul>'+xs.map(t=>'<li>'+esc(t)+'</li>').join('')+'</ul>';
 const cut=Math.ceil(plan.modules.length/2);
 const syllabus=(from:number,to:number)=>`<span class="kicker">Detailed module curriculum · ${from+1}-${to}</span><h2>${from===0?'Build the foundations.':'Apply, integrate and demonstrate.'}</h2><p>The module names, lesson sequence and evidence below match the course learning workspace.</p><div class="syllabus" data-count="${to-from}">${plan.modules.slice(from,to).map((mod:any,k:number)=>`<article class="card module"><h3><span class="module-number">${from+k+1}</span>${esc(mod.title)}</h3><p class="module-context">${esc(mod.context)}</p><ol>${mod.lessons.map((l:any)=>`<li><b>${l.key}</b><span><strong>${esc(l.title)}</strong>${to-from===4?'':esc(l.explanation.split(/(?<=\.)\s/)[0])}</span></li>`).join('')}</ol><p class="evidence-line"><b>You will produce:</b> ${esc(mod.evidence)}</p></article>`).join('')}</div>${to-from===2&&c.slug!=='space-tech'?'<div class="band"><h3>Practice is part of every module</h3><p>Work through the example, record your reasoning, complete the module assignment and compare your work with the review criteria.</p></div>':''}`;
 const sample=plan.modules[c.slug==='space-tech'?1:0];
 const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><title>${esc(c.title)} | Curriculum ${plan.version}</title><meta name="author" content="SamkhyaAcademy"><meta name="description" content="${esc(c.shortDescription)}"><link rel="stylesheet" href="../../assets/fonts.css"><link rel="stylesheet" href="../brochure.css"></head><body>
 ${wrap(1,`<span class="kicker">${esc(c.category)} · ${esc(c.level)}</span><h1>${esc(c.title)}</h1><p class="headline">${m.headline}</p><img class="cover-image" src="../../assets/course-visuals/${m.image}" alt="${esc(c.title)} illustration"><p class="dek">${esc(c.shortDescription)}</p><div class="facts"><div class="fact">${icon('Clock3')}${esc(c.durationText)}</div><div class="fact">${icon('Layers')}${plan.modules.length} modules</div><div class="fact">${icon('BookOpen')}${plan.lessons.length} lessons</div></div><a class="cta" href="${courseUrl}">Explore the course ${icon('ArrowRight')}</a><p class="note">Concepts, worked examples, assignments and a coherent course project.</p>`,true)}
 ${wrap(2,`<span class="kicker">Who it is for · What you will learn</span><h2>Your next capability.</h2><p class="dek">${esc(c.description)}</p><div class="outcomes">${c.outcomes.map((t,i)=>`<div class="outcome">${icon(['Target','Code2','ShieldCheck','Rocket'][i%4])}<p>${esc(t)}</p></div>`).join('')}</div><div class="grid2"><div class="card"><h3>${icon('Users')}Audience</h3>${list(c.audience)}</div><div class="card"><h3>${icon('ClipboardCheck')}Prerequisites</h3>${list(c.prerequisites)}</div></div><img class="diagram" src="../../assets/course-visuals/${c.slug}-roadmap.svg" alt="Course learning progression"><div class="band"><h3>One curriculum, three connected views</h3><p>This guide summarizes the same modules and lessons shown on the course overview and in the learning workspace. The next pages explain the scope and practical evidence for every module.</p></div>`)}
 ${wrap(3,syllabus(0,cut))}
 ${wrap(4,syllabus(cut,plan.modules.length))}
 ${wrap(5,`<span class="kicker">Projects and working methods</span><h2>${esc(m.project)}</h2><p class="dek">${esc(m.brief)}</p><div class="evidence">${m.evidence.map((t,i)=>`<div>${icon(['FolderCode','ClipboardCheck','Presentation'][i])}<h3>${esc(t)}</h3></div>`).join('')}</div><div class="card"><h3>${icon('Wrench')}Tools and methods</h3><div class="toolbox">${c.tools.map(t=>'<span>'+esc(t)+'</span>').join('')}</div><p class="note" style="margin-top:3mm">Tools are learning choices, not partner endorsements.</p></div><div class="band dark"><h3>Inside module ${c.slug==='space-tech'?2:1}: a worked example</h3><pre style="font:9pt/1.6 monospace;white-space:pre-wrap;overflow-wrap:anywhere;color:#eff4ff">${esc(sample.example)}</pre></div><p>${esc(sample.interpretation)}</p><div class="band"><h3>How your work is reviewed</h3><p>Show the artifact, explain your decisions, test the stated assumptions and identify limitations. Module assignments build toward the course project rather than replacing it with a single example.</p></div>`)}
 ${wrap(6,`<span class="kicker">Delivery, completion and next steps</span><h2>Know what you are signing up for.</h2><div class="grid2"><div class="card"><h3>${icon('CalendarDays')}Delivery</h3><p>${delivery} · ${esc(c.durationText)}</p><p style="margin-top:3mm">Confirm current schedule, cohort arrangements and enrollment terms with the academy.</p></div><div class="card"><h3>${icon('Award')}Completion requirements</h3><p>Complete the required coursework and module assignments${c.requiresPassingExam?', and pass the course assessment':''}.${c.certificateEnabled?' A course completion certificate is available after those requirements are met.':''}</p></div></div><h3>What the learning workspace includes</h3><div class="learning-process">${[['Layers','Follow the modules','Expand the curriculum and open the exact lesson you need.'],['Code2','Apply the concepts','Read explanations, inspect examples and complete module practice.'],['NotebookPen','Keep your evidence','Use resources, notes, discussion and assignments to support your learning.']].map(([i,t,p])=>`<div>${icon(i)}<h3>${t}</h3><p>${p}</p></div>`).join('')}</div><div class="band"><h3>${c.slug==='entrepreneurship'?'Course learning is separate from venture applications':'Learning commitments, not outcome guarantees'}</h3><p>${c.slug==='entrepreneurship'?'You can study all seven modules without submitting an idea. Idea submission is a separate application for venture evaluation and possible mentor-supported progression. Course completion does not imply venture admission, investor introduction or funding.':'Completion is not a placement, employment or performance guarantee. The course project is educational evidence; any production use requires appropriate review and validation.'}</p></div>${c.slug==='space-tech'?'<div class="card"><h3>Educational mission scope</h3><p>The CubeSat/CanSat-style capstone is a simulated or ground-based educational demonstrator. Launch, flight qualification and radio-spectrum approvals are not included or implied.</p></div>':''}<div class="band dark"><h3>Start with the curriculum. Continue with the first lesson.</h3><p>Review your starting point, download this guide and explore the connected course experience.</p></div><a class="cta" href="${entry}">Go to the first lesson ${icon('ArrowRight')}</a>${c.slug==='entrepreneurship'?'<a href="'+base+'/pages/010.html">Separate journey: submit an idea for venture evaluation</a>':''}<p class="fine">Client-review edition. The static learning workspace saves demonstration progress locally; production enrollment, assessment, communications and certificate issuance are not connected.</p>`)}
 </body></html>`;
 const file=path.join(dir,'html',c.slug+'.html');await writeFile(file,html);await page.goto(pathToFileURL(file).href);await page.evaluate(()=>document.fonts.ready);await page.emulateMedia({media:'print'});
 const layout=await page.evaluate(()=>({badImages:[...document.images].filter(x=>!x.complete||!x.naturalWidth).map(x=>x.src),overflow:[...document.querySelectorAll('.sheet')].flatMap((s,i)=>[...s.querySelectorAll('*')].filter(e=>!e.closest('.foot')&&e.getBoundingClientRect().bottom>s.getBoundingClientRect().bottom-49).map(e=>({page:i+1,text:e.textContent?.slice(0,80)})))}));
 if(layout.badImages.length||layout.overflow.length)throw Error(c.slug+' '+JSON.stringify(layout));
 await page.pdf({path:path.join(dir,brochureName(c)),format:'A4',printBackground:true,preferCSSPageSize:true,tagged:true});
 results.push({slug:c.slug,title:c.title,pdf:'brochures/'+brochureName(c),pages:6,version:plan.version,layout});console.log('PDF '+c.slug+' aligned '+plan.version);
}
await browser.close();await writeFile(path.join(dir,'manifest.json'),JSON.stringify(results,null,2));
