import {reviewPanel} from './review-panel.mjs';
import {existingLessons,lessonUrl} from './course-lesson-routes.mjs';
import {renderDedicatedLesson,lessonWorksheet} from './dedicated-lessons.mjs';
import {curriculum,moduleWorksheet} from './curriculum.mjs';
import {renderModuleLesson} from './module-lessons.mjs';
import {readFile,writeFile,mkdir,copyFile,readdir} from 'node:fs/promises';
import path from 'node:path';
import {courseCatalog} from '../../packages/catalog/src/index.ts';
import {additions,family,primary} from './data.mjs';
import {brochureName} from './marketing.mjs';
import {renderScreen,esc,icon} from './render.mjs';

const root=process.cwd(),out=path.join(root,'output','UX_REVIEW_ASTRA_2026_09_05');
await mkdir(path.join(out,'pages'),{recursive:true});await mkdir(path.join(out,'assets'),{recursive:true});await mkdir(path.join(out,'screens'),{recursive:true});
const source=await readFile(path.join(root,'scripts/capture-screen-inventory.ts'),'utf8');
const list=source.slice(source.indexOf('const screens:'),source.indexOf('const base ='));
const screens=[...list.matchAll(/n:\s*(\d+),\s*name:\s*"([^"]+)",\s*area:\s*"([^"]+)"/g)].map(m=>({n:Number(m[1]),name:m[2],area:m[3]}));
if(screens.length!==95)throw new Error(`Expected 95 baseline entries, found ${screens.length}`);
screens.push(...additions.map(([n,name,area])=>({n,name,area})));
const assets=[['reference-assets/venture-builder-workshop-v2.png','workshop.png'],['reference-assets/full-stack-instructor-v2.png','instructor.png']];
for(const [from,to] of assets)await copyFile(path.join(root,'apps/web/public',from),path.join(out,'assets',to));
for(const file of ['style.css','interactions.js','enrichment.css','enrichment.js'])await copyFile(path.join(root,'scripts/ux-rebuild',file),path.join(out,'assets',file));
function storedZip(files:Record<string,string|Buffer>){const local:Buffer[]=[],central:Buffer[]=[];let offset=0;for(const [name,text] of Object.entries(files)){const filename=Buffer.from(name),data=Buffer.from(text);let crc=0xffffffff;for(const byte of data){crc^=byte;for(let i=0;i<8;i++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}crc=(crc^0xffffffff)>>>0;const h=Buffer.alloc(30);h.writeUInt32LE(0x04034b50,0);h.writeUInt16LE(20,4);h.writeUInt32LE(crc,14);h.writeUInt32LE(data.length,18);h.writeUInt32LE(data.length,22);h.writeUInt16LE(filename.length,26);local.push(h,filename,data);const c=Buffer.alloc(46);c.writeUInt32LE(0x02014b50,0);c.writeUInt16LE(20,4);c.writeUInt16LE(20,6);c.writeUInt32LE(crc,16);c.writeUInt32LE(data.length,20);c.writeUInt32LE(data.length,24);c.writeUInt16LE(filename.length,28);c.writeUInt32LE(offset,42);central.push(c,filename);offset+=h.length+filename.length+data.length;}const cd=Buffer.concat(central),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50,0);end.writeUInt16LE(Object.keys(files).length,8);end.writeUInt16LE(Object.keys(files).length,10);end.writeUInt32LE(cd.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...local,cd,end]);}
await writeFile(path.join(out,'assets/profile-card-starter.zip'),storedZip({'profile-card/README.md':'# Profile card project\nBuild a responsive, semantic profile card. Open index.html in your browser.\n\nCheck headings, labels, keyboard focus and narrow-screen layout.','profile-card/index.html':'<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Profile card</title><link rel="stylesheet" href="styles.css"><main><article><h1>Priya Sharma</h1><p>Learning full-stack development.</p><button>View my projects</button></article></main></html>','profile-card/styles.css':'body{font:16px system-ui;background:#f4f2ff;color:#17204e;padding:24px}article{max-width:420px;background:white;border:1px solid #ded8fa;border-radius:12px;padding:24px}button{background:#4931ee;color:white;border:0;border-radius:6px;padding:12px 18px}','profile-card/checklist.md':'- [ ] Semantic heading\n- [ ] Descriptive button\n- [ ] Responsive width\n- [ ] Visible keyboard focus'}));
const brochureFiles:Record<string,Buffer>={};
for(const course of courseCatalog)brochureFiles[brochureName(course)]=await readFile(path.join(out,'brochures',brochureName(course)));
await writeFile(path.join(out,'brochures/all-course-brochures.zip'),storedZip(brochureFiles));
const cssFiles=(await readdir(path.join(root,'apps/web/.next/static/css'))).filter(f=>f.endsWith('.css'));let fonts='';
for(const file of cssFiles){const css=await readFile(path.join(root,'apps/web/.next/static/css',file),'utf8');for(const match of css.matchAll(/@font-face\{[^}]*font-family:Poppins;[^}]*\}/g)){const face=match[0];const f=face.match(/media\/([^)]*\.woff2)/)?.[1];if(f){await copyFile(path.join(root,'apps/web/.next/static/media',f),path.join(out,'assets',f));fonts+=face.replace(/\/_next\/static\/media\//g,'./')+'\n';}}}
if(!fonts)throw new Error('No local Poppins font faces found.');await writeFile(path.join(out,'assets/fonts.css'),fonts);
for(const s of screens)await writeFile(path.join(out,'pages',`${String(s.n).padStart(3,'0')}.html`),renderScreen(s,courseCatalog));
await mkdir(path.join(out,'assets/lesson-resources'),{recursive:true});
const aligned=[];
for(const c of courseCatalog){
 const plan=curriculum(c);aligned.push({slug:c.slug,version:plan.version,modules:plan.modules.map(m=>({title:m.title,evidence:m.evidence,lessons:m.lessons.map(l=>({title:l.title,file:l.file}))}))});
 for(const [m,mod] of plan.modules.entries()){
  await writeFile(path.join(out,'assets/lesson-resources',c.slug+'-module-'+(m+1)+'.md'),moduleWorksheet(c,m));
  for(const [l,lesson] of mod.lessons.entries())await writeFile(path.join(out,'pages',lesson.file),renderModuleLesson(c,m,l));
 }
}
await writeFile(path.join(out,'CURRICULUM_ALIGNMENT.json'),JSON.stringify(aligned,null,2));
await writeFile(path.join(out,'COURSE_LESSON_LINKS.md'),'# Course lessons\n\n12 courses, 56 modules and 224 connected lessons. Notes and progress are browser-local. Venture applications are separate from course learning.\n\n[Browse every module and lesson](MODULE_LESSON_INDEX.html)\n\n'+courseCatalog.map(c=>'- ['+c.title+'](pages/'+lessonUrl(c.slug)+')').join('\n'));
await writeFile(path.join(out,'MODULE_LESSON_INDEX.html'),`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Module and lesson review index</title><link rel="stylesheet" href="assets/fonts.css"><link rel="stylesheet" href="assets/style.css"></head><body><main class="screen-gallery"><h1>Courses, modules and lessons</h1><p>Separate client-review directory. 56 modules and 224 lessons; course learning does not submit a venture application.</p><a class="button section" href="pages/001.html">Open academy</a><div class="grid2 section">${courseCatalog.map(c=>`<section class="card"><h2>${esc(c.title)}</h2>${curriculum(c).modules.map((m,i)=>`<details class="module section"><summary>Module ${i+1}: ${esc(m.title)}</summary><div class="lessons">${m.lessons.map(l=>`<a href="pages/${l.file}">${l.key} ${esc(l.title)}</a>`).join('')}</div></details>`).join('')}</section>`).join('')}</div></main></body></html>`);
for(const file of ['dedicated-lessons.css','dedicated-lessons.js','layout-fixes.css','module-lessons.css','module-lessons.js'])await copyFile(path.join(root,'scripts/ux-rebuild',file),path.join(out,'assets',file));
await writeFile(path.join(out,'manifest.json'),JSON.stringify(screens.map(s=>({...s,family:family(s.n),page:`pages/${String(s.n).padStart(3,'0')}.html`,screenshot:`screens/${String(s.n).padStart(3,'0')}.png`,next:primary[s.n],status:'Interactive front-end prototype; production services not connected'})),null,2));
const cards=screens.map(s=>`<article class="gallery-card" data-search="${esc(s.n+' '+s.name+' '+s.area)}"><a href="pages/${String(s.n).padStart(3,'0')}.html"><img loading="lazy" src="screens/${String(s.n).padStart(3,'0')}.png" alt="Screen ${s.n}: ${esc(s.name)}"></a><div><small>${String(s.n).padStart(3,'0')} · ${esc(s.area)}</small><h2>${esc(s.name)}</h2><div class="actions"><a class="button small primary" href="pages/${String(s.n).padStart(3,'0')}.html">${icon('MousePointer2')}Open working screen</a><a class="button small" href="screens/${String(s.n).padStart(3,'0')}.png">${icon('Image')}PNG</a></div></div></article>`).join('');
await writeFile(path.join(out,'index.html'),`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SamkhyaAcademy · New UX review</title><link rel="stylesheet" href="assets/fonts.css"><link rel="stylesheet" href="assets/style.css"><link rel="stylesheet" href="assets/enrichment.css"></head><body><main class="screen-gallery"><div class="heading"><div><span class="eyebrow">SamkhyaAcademy · 5 September 2026</span><h1>Connected learning-platform UX</h1><p>${screens.length} newly rendered screens · 95 rebuilt baseline states + ${additions.length} continuation states</p></div><a class="button primary" href="pages/001.html">Start the experience ${icon('ArrowRight')}</a></div>${reviewPanel(icon,true)}<div class="callout purple"><b>Review the working screens</b><p>Open a screen to use the controls and follow the journey. Local prototype state is saved in your browser. Authentication, native C/C++ compilation, video media, payment and communication services are not connected. See the verification report for measured results.</p></div><div class="review-nav section"><a href="pages/183.html">Learning experiences</a><a href="pages/158.html">Brochure library</a><a href="pages/146.html">Investor & founder journeys</a><a href="ENRICHMENT_REPORT.md">Latest changes</a><a href="ASTRA_UX_REBUILD_BRIEF.md">Design brief</a><a href="SCREEN_INVENTORY.md">Inventory</a><a href="MARVEL_PROTOTYPE_MAP.csv">Hotspot map</a><a href="REFERENCE_COMPARISON.html">Reference comparison</a><a href="VERIFICATION_REPORT.md">Verification report</a><button class="button small" id="reset-demo">Reset demo state</button></div><label class="search section">${icon('Search')}<input id="gallery-search" placeholder="Find a screen number, course, stage or workflow…" aria-label="Search screens"></label><div class="gallery-grid section">${cards}</div></main><script>document.getElementById('gallery-search').addEventListener('input',e=>document.querySelectorAll('[data-search]').forEach(c=>c.hidden=!c.dataset.search.toLowerCase().includes(e.target.value.toLowerCase())));document.getElementById('reset-demo').addEventListener('click',()=>{localStorage.removeItem('samkhya-ux-v2');document.getElementById('reset-demo').textContent='Demo state reset';});</script></body></html>`);
const md=[`# New ${screens.length}-screen UX review`,'', 'Status: interactive front-end prototype. Existing IDs 1–95 are retained; 96 onward fill journey gaps. Screens are not claims of backend implementation or design approval.','', '| ID | Screen | Family | Working page | PNG | Next |','|---:|---|---|---|---|---:|',...screens.map(s=>`| ${s.n} | ${s.name} | ${family(s.n)} | [Open](pages/${String(s.n).padStart(3,'0')}.html) | [PNG](screens/${String(s.n).padStart(3,'0')}.png) | ${primary[s.n]} |`)];
await writeFile(path.join(out,'SCREEN_INVENTORY.md'),md.join('\n'));
await copyFile(path.join(root,'docs/ux/ASTRA_UX_REBUILD_BRIEF.md'),path.join(out,'ASTRA_UX_REBUILD_BRIEF.md'));
await writeFile(path.join(out,'README.md'),'# SamkhyaAcademy new UX review\n\nOpen index.html for all screens, searchable by number or title. Each card opens the interactive HTML and its freshly captured PNG.\n\nFor consistent browser storage and clipboard behavior, serve this folder with `node scripts/ux-rebuild/serve.mjs` from the repository and open http://127.0.0.1:4310.\n\nThis is a customer UX prototype. Local interactions are real browser behavior; backend integrations are not connected. See VERIFICATION_REPORT.md.\n');
console.log(`Built ${screens.length} screens in ${out}`);
