import {courseDepth} from './course-depth.mjs';
import {marketing,courseScreens} from './marketing.mjs';
import {header,esc,icon} from './render.mjs';
export function lessonWorksheet(c){
 const d=courseDepth[c.slug];
 return '# '+c.title+'\n\n## '+d.topic+'\n\n'+d.scenario+'\n\n'+d.explanation+'\n\n## Worked example\n\n'+d.example+'\n\n'+d.result+'\n\n## Practice\n\n'+d.tasks.map((t,i)=>(i+1)+'. '+t+'\n   Your evidence: ').join('\n\n')+'\n\n## Review criteria\n\n'+d.criteria.map(t=>'- [ ] '+t).join('\n')+'\n\n## Reflection\n\n'+d.question+'\n\nYour explanation: \n';
}
export function renderDedicatedLesson(c){
 const d=courseDepth[c.slug],m=marketing[c.slug],back=String(courseScreens[c.slug]).padStart(3,'0')+'.html';
 const sections=[['context','Brief & outcomes','Compass'],['concept','Understand the concept','BookOpen'],['example','Worked example','Code2'],['practice','Practice & evidence','ClipboardList'],['check','Knowledge check','BadgeCheck'],['notes','Notes & discussion','MessagesSquare']];
 const list=items=>'<ul class="checklist">'+items.map(t=>'<li>'+icon('Check')+'<span>'+esc(t)+'</span></li>').join('')+'</ul>';
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(d.topic)} · ${esc(c.title)}</title><link rel="stylesheet" href="../assets/fonts.css"><link rel="stylesheet" href="../assets/style.css"><link rel="stylesheet" href="../assets/enrichment.css"><link rel="stylesheet" href="../assets/dedicated-lessons.css"><link rel="stylesheet" href="../assets/layout-fixes.css"></head><body data-course="${esc(c.slug)}">${header('lesson',0)}<main class="wrap dedicated-lesson"><div class="breadcrumb"><a href="002.html">Courses</a>${icon('ChevronRight')}<a href="${back}">${esc(c.title)}</a>${icon('ChevronRight')}<span>Learning workspace</span></div><div class="heading"><div><span class="eyebrow">${esc(c.title)}</span><h1>${esc(d.topic)}</h1><p>Learn the principle. Follow the example. Build evidence of your understanding.</p></div><a class="button" href="${back}">${icon('ArrowLeft')}Course overview</a></div><div class="lesson-layout">
 <aside class="lesson-sidebar"><section class="card"><h3>${icon('BookOpenCheck')}Lesson progress</h3><p id="completion-label" class="section">Not completed</p><div class="progress" role="progressbar" aria-label="Lesson completion" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><i id="lesson-progress" style="width:0%"></i></div></section><nav class="lesson-outline" aria-label="Lesson sections">${sections.map(([id,title,i],n)=>`<a href="#${id}">${icon(i)}<span><small>0${n+1}</small>${title}</span>${icon('ChevronRight')}</a>`).join('')}</nav><section class="card section"><h3>${icon('Route')}Course journey</h3><ol class="journey-list">${m.stages.map(t=>'<li>'+esc(t)+'</li>').join('')}</ol><a href="${back}#curriculum" class="button small">${icon('Layers')}View curriculum</a></section></aside>
 <div class="lesson-main stack"><section id="context" class="reader"><div class="lesson-banner"><img src="../assets/course-visuals/${m.image}" alt="${esc(c.title)}"><div><span class="eyebrow">Your learning brief</span><h2>${esc(m.headline)}</h2></div></div><h3>${icon('Compass')}The situation</h3><p>${esc(d.scenario)}</p><h3>${icon('Target')}What good work looks like</h3>${list(d.criteria)}</section>
 <section id="concept" class="reader"><span class="eyebrow">01 · Understand</span><h2>${icon('BookOpen')}The core principle</h2><p>${esc(d.explanation)}</p><div class="callout purple"><b>Connect it to the project</b><p>${esc(m.brief)}</p></div></section>
 <section id="example" class="reader"><div class="cardhead"><h2>${icon('Code2')}Work through the example</h2><button class="button small" id="copy-example">${icon('Copy')}Copy</button></div><pre id="worked-example" class="code-display">${esc(d.example)}</pre><h3>${icon('ScanLine')}Read the result</h3><p>${esc(d.result)}</p></section>
 <section id="practice" class="reader"><span class="eyebrow">02 · Apply</span><h2>${icon('ClipboardList')}Build your evidence</h2><p>Use the worked example as a starting point. Record assumptions, test cases and the evidence supporting your decision.</p><form id="practice-form">${d.tasks.map((t,i)=>`<label class="practice-task"><b>${i+1}. ${esc(t)}</b><textarea name="task-${i}" rows="3" placeholder="Write your approach, result and evidence…"></textarea></label>`).join('')}<button class="button primary" type="submit">${icon('Save')}Save practice</button><span class="save-status" id="practice-status" role="status"></span></form></section>
 <section id="check" class="reader"><span class="eyebrow">03 · Reflect</span><h2>${icon('BadgeCheck')}Check your understanding</h2><p>${esc(d.question)}</p><label>Your reasoning<textarea id="reflection" rows="3" placeholder="Explain your answer before revealing the guide…"></textarea></label><details class="section"><summary>Compare with the explanation</summary><p class="section">${esc(d.answer)}</p></details><div class="section">${d.criteria.map((t,i)=>`<label class="check-row"><input type="checkbox" data-evidence="${i}"><span>${esc(t)}</span></label>`).join('')}</div><button class="button primary section" id="complete-lesson">${icon('CheckCheck')}Mark complete</button><p id="complete-status" role="status"></p></section>
 <section id="notes" class="reader"><h2>${icon('NotebookPen')}Your notes</h2><label>Private lesson notes<textarea id="lesson-notes" rows="4" placeholder="Capture an insight or a question to revisit…"></textarea></label><p class="metric-note">Practice, notes and completion are saved on this browser only.</p><h3>${icon('MessagesSquare')}Lesson discussion</h3><form id="discussion-form"><label>Add a question or insight<textarea id="discussion-text" required maxlength="2000" rows="2" placeholder="What would you like to discuss?"></textarea></label><button class="button section" type="submit">${icon('Send')}Post locally</button></form><p class="metric-note">Prototype discussion: visible only in this browser, not sent to a mentor.</p><div id="discussion-list"></div></section></div>
 <aside class="stack"><section class="card"><h3>${icon('FolderDown')}Lesson resources</h3><a class="row" href="../assets/lesson-resources/${c.slug}.md" download>${icon('FileText')}<span>Worked example & worksheet<small>Markdown · editable and downloadable</small></span>${icon('Download')}</a><a class="row" href="#practice">${icon('ClipboardCheck')}Practice tasks${icon('ArrowRight')}</a><a class="row" href="#check">${icon('BadgeCheck')}Self-review checklist${icon('ArrowRight')}</a></section><section class="card"><h3>${icon(m.icon)}Your course project</h3><h2 class="section">${esc(m.project)}</h2><p class="section">${esc(m.brief)}</p><div class="section">${list(m.evidence)}</div></section><section class="card"><h3>${icon('Lightbulb')}Learning tip</h3><p class="section">Explain the result in your own words. Change one assumption, then describe how the outcome would change.</p><a class="button section" href="#notes">${icon('NotebookPen')}Capture your thinking</a></section><section class="card"><h3>${icon('LibraryBig')}Keep exploring</h3><a class="row" href="${back}#curriculum">${icon('Layers')}Course curriculum</a><a class="row" href="002.html">${icon('Search')}Explore all courses</a></section></aside></div></main><script src="../assets/enrichment.js" defer></script><script src="../assets/dedicated-lessons.js" defer></script></body></html>`;
}
