export function experienceHub(courses,h){const {heading,link,icon,esc}=h;
const formats=[
['Free text course','C Programming Fundamentals','Read explanations, follow code examples and continue into guided practice.',87,'Terminal','programming-foundations.png'],
['Video course','Full-Stack Development','Instructor-led layout with curriculum sidebar, playback controls, progress and resources.',82,'PlayCircle','full-stack-hero-v2.png'],
['Text course','Full Stack: HTML Structure','The same learning workspace, with a readable article instead of a video player.',83,'BookOpen','full-stack-hero-v2.png'],
['Text + video course','Full Stack: worked example','Move between the video explanation, written example and hands-on practice.',84,'PanelsTopLeft','full-stack-hero-v2.png'],
['Free C++ course','C++ Essentials','Explore the video lesson demonstration, then practice with vectors.',89,'Braces','programming-foundations.png'],
['Paid interactive course','Data Structures & Algorithms','Step through graph traversal and linked-list operations with SVG visualizations.',91,'Network','dsa-graph.svg']];
return heading('Explore the complete learning experience','Choose a format, open a real prototype lesson, then follow practice, assessment and certification.',link('Download all brochures',158,'Download'))+
`<div class="callout purple section"><b>One learning workspace, multiple content formats</b><p>Curriculum navigation, progress, resources, notes and discussion remain consistent. Video playback is a storyboard demonstration; C/C++ exercises use guided traces, not a connected compiler.</p></div><div class="program-grid">${formats.map(([type,title,desc,n,i,img])=>`<article class="card program-card"><img class="catalog-photo" src="../assets/course-visuals/${img}" alt="${esc(title)}"><div class="copy"><span class="eyebrow">${icon(i)}${type}</span><h2>${title}</h2><p>${desc}</p>${link('Open '+type.toLowerCase(),n,i,'button primary')}</div></article>`).join('')}</div><section class="card section"><div class="cardhead"><h2>${icon('Award')}From learning to certification</h2>${link('My learning dashboard',18,'LayoutDashboard')}</div><div class="grid4">${[[109,'Completion checklist','Check lesson, practice and assessment requirements.','ListChecks'],[21,'Assessment instructions','Review the rules before starting the assessment.','ClipboardCheck'],[23,'Results & next steps','Inspect the result and improvement path.','ChartNoAxesCombined'],[24,'Certificate example','View the illustrative certificate and verification link.','Award']].map(([n,t,d,i])=>`<article class="card"><h3>${icon(i)}${t}</h3><p class="section">${d}</p>${link('Open example',n,'ArrowRight')}</article>`).join('')}</div><div class="actions section">${link('Take exam example',22,'Pencil')}${link('Retry & improvement',110,'RotateCcw')}${link('Verification not found',111,'Search')}</div></section><section class="card section"><h2>More of the learner journey</h2><div class="actions section">${[[54,'Code editor & live preview','Code2'],[58,'Download project files','FolderCode'],[69,'Notes','NotebookPen'],[70,'Lesson discussion','MessagesSquare'],[107,'Hybrid schedule','CalendarDays'],[108,'Offline attendance','Users'],[59,'Blogs & community','Newspaper'],[62,'Content authoring','FilePen'],[95,'Review & publishing','ShieldCheck']].map(([n,t,i])=>link(t,n,i)).join('')}</div></section><section class="card section"><div class="cardhead"><h2>All ${courses.length} courses</h2>${link('All PDFs · no form required',158,'Download')}</div><div class="grid3">${courses.map(c=>`<a class="button" href="${String(h.courseScreens[c.slug]).padStart(3,'0')}.html">${icon('BookOpen')}${esc(c.title)}</a>`).join('')}</div></section>`;
}
