// Presentation copy complements, but never overrides, the canonical course catalog.
export const marketing = {
 'ai-engineering':{image:'ai-engineering-hero-v2.png',icon:'Bot',accent:'#17bbd8',headline:'Move from AI experiments to dependable systems.',stages:['Discover','Ground','Build','Evaluate','Deploy','Improve'],project:'Enterprise knowledge assistant',brief:'Frame a real information need, connect permitted sources, build a grounded assistant and present an evaluation and human-review plan.',evidence:['Task and integration map','Grounded response examples','Evaluation and operational runbook']},
 'ai-leadership':{image:'ai-leadership-hero-v2.png',icon:'Compass',accent:'#bb9d59',headline:'Lead AI adoption with clarity and evidence.',stages:['Understand','Prioritize','Govern','Pilot','Measure','Scale'],project:'AI adoption decision portfolio',brief:'Turn a business opportunity into a prioritized use-case portfolio, pilot proposal and responsible operating model.',evidence:['Use-case prioritization','Governance and ownership map','Pilot measurement plan']},
 'applied-ml-engineering':{image:'applied-ml-engineering.png',icon:'BrainCircuit',accent:'#9871ff',headline:'Build models. Test assumptions. Deliver useful ML.',stages:['Frame','Prepare','Train','Validate','Serve','Monitor'],project:'End-to-end prediction service',brief:'Prepare a dataset, establish a baseline, compare models and package a reproducible prediction workflow with documented limitations.',evidence:['Reproducible data pipeline','Model evaluation report','Prediction service and monitoring plan']},
 'full-stack':{image:'full-stack-hero-v2.png',icon:'Code2',accent:'#448dff',headline:'Build the entire application, not just one layer.',stages:['Structure','Style','Interact','Connect','Secure','Ship'],project:'A complete web application',brief:'Build a responsive interface, connect an API and database, implement access rules and prepare a tested deployment.',evidence:['Responsive user interface','API and data model','Tested release and project README']},
 'data-analytics':{image:'data-analytics.png',icon:'ChartNoAxesCombined',accent:'#20c4ae',headline:'Turn raw data into a clear decision.',stages:['Ask','Collect','Clean','Explore','Visualize','Explain'],project:'Decision-ready analytics report',brief:'Investigate a practical business question, prepare the data, explore patterns and communicate findings with a clear dashboard and caveats.',evidence:['Documented queries and cleaning','Interactive dashboard','Evidence-based recommendation']},
 'cybersecurity':{image:'cybersecurity-hero-v2.png',icon:'ShieldCheck',accent:'#25d2b2',headline:'Understand the threat. Build the defense.',stages:['Understand','Harden','Observe','Investigate','Respond','Review'],project:'Defensive security investigation',brief:'Work within an authorized lab, identify weaknesses, inspect evidence and develop a remediation and incident-response report.',evidence:['Threat and risk assessment','Lab investigation evidence','Remediation and response playbook']},
 'space-tech':{image:'space-tech-hero-v2.png',icon:'Orbit',accent:'#57bdfb',headline:'Connect space systems to problems on Earth.',stages:['Mission','Orbit','Payload','Ground','Analyze','Validate'],project:'Mission concept and satellite-data application',brief:'Define a mission objective, reason about system trade-offs and demonstrate an application of satellite or geospatial data.',evidence:['Mission concept and trade study','System and ground-segment diagram','Data application and validation notes']},
 'entrepreneurship':{image:'entrepreneurship-hero-v2.png',icon:'Rocket',accent:'#23b492',headline:'Build your venture one validated step at a time.',stages:['Idea','Validate','Model','MVP','Pilot','Traction','Scale'],project:'A reviewed venture evidence portfolio',brief:'Develop a problem statement, gather customer evidence, build and test an MVP and refine your venture through mentor-reviewed stage gates.',evidence:['Customer validation and business model','MVP and pilot evidence','Pitch narrative and stage-review history']},
 'c-programming-fundamentals':{image:'programming-foundations.png',icon:'Terminal',accent:'#5ba6ef',headline:'Start with C. Learn how programs really work.',stages:['Set up','Control','Functions','Memory','Files','Build'],project:'Command-line record manager',brief:'Use functions, structures and file operations to create a small terminal application and explain how its data moves through memory.',evidence:['Readable C source files','Input and boundary-case tests','Memory and file-handling explanation']},
 'cpp-essentials':{image:'programming-foundations.png',icon:'Braces',accent:'#7998ff',headline:'Write clearer C++ with objects and ownership.',stages:['Syntax','Objects','Containers','Algorithms','Ownership','Build'],project:'A modern C++ console application',brief:'Model a practical problem with classes, use standard containers and algorithms, and explain resource ownership in your solution.',evidence:['Class and ownership design','Container and algorithm examples','Tested console project']},
 'javascript-foundations':{image:'programming-foundations.png',icon:'FileCode2',accent:'#e3bd53',headline:'Make the web respond to your ideas.',stages:['Values','Functions','Objects','DOM','Async','Build'],project:'Interactive browser application',brief:'Combine events, DOM updates and asynchronous behavior in a small web application that people can use and understand.',evidence:['Interactive interface','Documented event and data flow','Responsive project and test notes']},
 'data-structures-algorithms':{image:'dsa-graph.svg',icon:'Network',accent:'#ac86ff',headline:'See the algorithm. Understand every step.',stages:['Analyze','Arrays','Lists','Trees','Graphs','Optimize'],project:'Visual algorithm explorer',brief:'Trace data structures, compare approaches and build a small visual explanation of an algorithm with test cases and complexity analysis.',evidence:['Step-by-step graph or tree trace','Correctness and edge-case tests','Time and space complexity explanation']}
};
export const courseScreens={'ai-engineering':4,'ai-leadership':11,'applied-ml-engineering':5,'full-stack':6,'data-analytics':13,'cybersecurity':14,'space-tech':12,'entrepreneurship':9,'c-programming-fundamentals':86,'cpp-essentials':88,'javascript-foundations':15,'data-structures-algorithms':90};
export const brochureRoutes=Object.fromEntries(Object.keys(marketing).map((slug,i)=>[slug,i===0?[43,143]:[157+i*2,158+i*2]]));
export const courseGate=(c)=>`../brochures/${brochureName(c)}`;
export const brochureName=c=>(c.brochurePublicPath||`/brochures/${c.slug}.pdf`).split('/').pop();
export function conceptSvg(c){const m=marketing[c.slug];return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 340" role="img" aria-label="${c.title.replaceAll("&","&amp;")}: ${m.stages.join(' to ')}"><defs><linearGradient id="bg" x2="1" y2="1"><stop stop-color="#091a40"/><stop offset="1" stop-color="#182d5c"/></linearGradient></defs><rect width="1000" height="340" rx="24" fill="url(#bg)"/><path d="M90 160H910" stroke="${m.accent}" stroke-width="3" stroke-dasharray="5 8"/>${m.stages.map((v,i)=>{const x=90+i*820/(m.stages.length-1);return `<circle cx="${x}" cy="160" r="36" fill="#112650" stroke="${m.accent}" stroke-width="2"/><text x="${x}" y="169" text-anchor="middle" fill="white" font-family="Arial" font-size="26">${i+1}</text><text x="${x}" y="235" text-anchor="middle" fill="white" font-family="Arial" font-size="20">${v}</text>`;}).join('')}<text x="40" y="55" fill="${m.accent}" font-family="Arial" font-size="16" letter-spacing="3">FROM CONCEPT TO EVIDENCE</text></svg>`;}
