import {header,esc,icon} from './render.mjs';
import {curriculum} from './curriculum.mjs';
import {courseScreens,marketing,brochureName} from './marketing.mjs';
export function renderModuleLesson(c,mi,li){
 const plan=curriculum(c),mod=plan.modules[mi],lesson=mod.lessons[li],index=plan.lessons.findIndex(x=>x.file===lesson.file),prev=plan.lessons[index-1],next=plan.lessons[index+1],back=String(courseScreens[c.slug]).padStart(3,'0')+'.html';
 const a=(title,url,i='ArrowRight',cls='button')=>`<a class="${cls}" href="${url}">${icon(i)}${esc(title)}</a>`;
 const worksheet=`../assets/lesson-resources/${c.slug}-module-${mi+1}.md`;
 const practice=c.slug==='data-structures-algorithms'?a('Open graph simulation','091.html','Network')+a('Explore linked lists','092.html','Workflow'):c.slug==='c-programming-fundamentals'&&mi===2?a('Open C practice','112.html','Terminal'):c.slug==='cpp-essentials'&&mi===2?a('Open C++ practice','113.html','Braces'):c.slug==='full-stack'&&mi===0?a('Open browser practice','054.html','Code2'):'';
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(lesson.title)} · ${esc(c.title)}</title><link rel="stylesheet" href="../assets/fonts.css"><link rel="stylesheet" href="../assets/style.css"><link rel="stylesheet" href="../assets/enrichment.css"><link rel="stylesheet" href="../assets/layout-fixes.css"><link rel="stylesheet" href="../assets/module-lessons.css"></head><body data-course="${esc(c.slug)}" data-lesson="${lesson.key}" data-total="${plan.lessons.length}" data-curriculum-version="${plan.version}">${header('lesson',0)}<main class="wrap module-workspace"><div class="breadcrumb"><a href="002.html">Courses</a>${icon('ChevronRight')}<a href="${back}">${esc(c.title)}</a>${icon('ChevronRight')}<span>Module ${mi+1}</span></div><div class="heading"><div><h1>${esc(c.title)}</h1><p>${esc(c.shortDescription)}</p></div>${a('Course overview',back,'ArrowLeft')}</div>
 <div class="lesson-layout"><aside class="lesson-sidebar"><section class="card"><div class="cardhead"><b>Overall progress</b><b id="progress-label">0%</b></div><div class="progress" role="progressbar" aria-label="Course progress" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><i id="progress-fill" style="width:0%"></i></div><p class="metric-note">${plan.modules.length} modules · ${plan.lessons.length} lessons</p></section><nav aria-label="Course modules">${plan.modules.map((u,m)=>`<details class="module" ${m===mi?'open':''}><summary>${icon('ChevronRight')}<span>Module ${m+1}: ${esc(u.title)}</span><small data-module-count="${m+1}">0/${u.lessons.length}</small></summary><div class="lessons">${u.lessons.map(l=>`<a href="${l.file}" data-lesson-link="${l.key}" ${l.key===lesson.key?'class="active" aria-current="page"':''}>${icon('Circle')}<span>${l.key} &nbsp; ${esc(l.title)}</span></a>`).join('')}</div></details>`).join('')}</nav><section class="card section"><h3>${icon('GraduationCap')}Learning, not admission</h3><p class="section">${c.slug==='entrepreneurship'?'This course can be completed without submitting a venture idea. Course progress does not imply venture acceptance or funding.':'Completion records your learning in this browser. Production assessment and certificate issuance are separate services.'}</p></section></aside>
 <div class="lesson-main"><div class="lesson-title"><div><span class="eyebrow">Module ${mi+1} · Lesson ${lesson.key}</span><h2>${esc(lesson.title)}</h2><p>${esc(mod.title)}</p></div><button class="button" id="bookmark">${icon('Bookmark')}Bookmark</button></div><div role="tablist" aria-label="Lesson tools" class="tabs lesson-tabs">${[['overview','Overview','BookOpen'],['resources','Resources','FolderDown'],['notes','Notes','NotebookPen'],['discussion','Q&A','MessagesSquare'],['assignment','Assignment','ClipboardList']].map(([id,t,i],n)=>`<button id="tab-${id}" role="tab" aria-controls="panel-${id}" aria-selected="${n===0}" tabindex="${n===0?0:-1}" data-tab="${id}">${icon(i)}${t}</button>`).join('')}</div>
 <section id="panel-overview" role="tabpanel" aria-labelledby="tab-overview" class="reader"><span class="eyebrow">Understand and apply</span><h2>${esc(lesson.title)}</h2><p class="lesson-lead">${esc(lesson.explanation)}</p><h3>${icon('Compass')}Why this matters in the module</h3><p>${esc(mod.context)}</p><div class="cardhead"><h3>${icon('Code2')}Module worked example</h3><button class="button small" id="copy-example">${icon('Copy')}Copy example</button></div><pre class="code-display" id="worked-example">${esc(mod.example)}</pre><h3>${icon('ScanLine')}Interpret the result</h3><p>${esc(mod.interpretation)}</p><div class="callout purple"><b>Apply lesson ${lesson.key}</b><p>Explain how ${esc(lesson.title.toLowerCase())} affects the example above. Identify one assumption, change it, and describe what you would test before accepting the result.</p></div><h3>${icon('BadgeCheck')}Module knowledge check</h3><p>${esc(mod.question)}</p><label>Your reasoning<textarea id="reflection" rows="3" placeholder="Write your answer before comparing it with the explanation…"></textarea></label><details class="section"><summary>Compare with the explanation</summary><p class="section">${esc(mod.answer)}</p></details>${practice?'<div class="actions section">'+practice+'</div>':''}</section>
 <section id="panel-resources" role="tabpanel" aria-labelledby="tab-resources" class="reader" hidden><h2>${icon('FolderDown')}Module resources</h2><p>Keep the complete module reading, worked example and assignment together.</p><a class="button" href="${worksheet}" download>${icon('Download')}Download module worksheet</a><a class="button section" href="../brochures/${brochureName(c)}" download>${icon('BookOpen')}Download course brochure</a><h3>Required evidence</h3><p>${esc(mod.evidence)}</p>${practice?'<div class="actions section">'+practice+'</div>':''}</section>
 <section id="panel-notes" role="tabpanel" aria-labelledby="tab-notes" class="reader" hidden><h2>${icon('NotebookPen')}Private lesson notes</h2><label>Your notes<textarea id="lesson-notes" rows="8" placeholder="Record decisions, examples and questions for this lesson…"></textarea></label><p class="metric-note">Saved automatically on this browser, separately for each lesson.</p><button class="button" id="export-notes">${icon('Download')}Export notes</button></section>
 <section id="panel-discussion" role="tabpanel" aria-labelledby="tab-discussion" class="reader" hidden><h2>${icon('MessagesSquare')}Lesson discussion</h2><form id="discussion-form"><label>Question or insight<textarea id="discussion-text" rows="3" required maxlength="2000"></textarea></label><button class="button primary section" type="submit">${icon('Send')}Post locally</button></form><p class="metric-note">Local UX discussion only. No message is sent to an instructor.</p><div id="discussion-list"></div></section>
 <section id="panel-assignment" role="tabpanel" aria-labelledby="tab-assignment" class="reader" hidden><h2>${icon('ClipboardList')}Module assignment</h2><p>${esc(mod.evidence)}</p><form id="practice-form">${mod.tasks.map((t,i)=>`<label class="practice-task">${i+1}. ${esc(t)}<textarea name="task-${i}" rows="3" placeholder="Record your approach and evidence…"></textarea></label>`).join('')}<button class="button primary section" type="submit">${icon('Save')}Save assignment</button><p id="practice-status" role="status"></p></form><p class="metric-note">The assignment is shared across this module’s lessons and saved on this browser.</p></section>
 <section class="card section"><label class="check-row"><input type="checkbox" id="reviewed"><span>I have worked through this lesson and recorded my reasoning.</span></label><div class="actions"><button class="button primary" id="complete-lesson">${icon('CheckCheck')}Mark complete</button>${next?a('Next lesson',next.file):a('Review course',back,'BookOpen')}</div><p id="lesson-status" role="status" class="metric-note"></p></section><div class="lesson-pagination section">${prev?a('Previous lesson',prev.file,'ArrowLeft'):'<span>First lesson</span>'}<span>${index+1} / ${plan.lessons.length}</span>${next?a('Continue',next.file):a('Course overview',back)}</div></div>
 <aside class="stack"><section class="card"><h3>${icon('PlayCircle')}Continue learning</h3><p class="section">${next?esc(next.key+' '+next.title):'You reached the final lesson. Review your module assignments and completion record.'}</p>${next?a('Next lesson',next.file,'ArrowRight','button primary section'):a('Review curriculum',back+'#curriculum','Layers','button section')}</section><section class="card"><h3>${icon('FolderDown')}Course resources</h3><a class="row" href="${worksheet}" download>${icon('FileText')}Module ${mi+1} worksheet${icon('Download')}</a><a class="row" href="../brochures/${brochureName(c)}" download>${icon('BookOpen')}Course brochure${icon('Download')}</a></section><section class="card"><h3>${icon('Target')}Module deliverable</h3><p class="section">${esc(mod.evidence)}</p></section><section class="card"><h3>${icon(marketing[c.slug].icon)}Course details</h3><div class="row">${icon('Clock3')}${esc(c.durationText)}</div><div class="row">${icon('Layers')}${plan.modules.length} modules · ${plan.lessons.length} lessons</div><div class="row">${icon('Award')}${c.requiresPassingExam?'Coursework + passing assessment':'Required coursework'}</div><p class="metric-note">Local completion does not issue a certificate.</p></section>${c.slug==='entrepreneurship'?'<section class="card"><h3>'+icon('Lightbulb')+'Have a venture idea?</h3><p class="section">Optional and separate from this course: apply for venture evaluation.</p>'+a('Submit an idea','010.html','ArrowRight','button section')+'</section>':''}</aside></div></main><script src="../assets/enrichment.js" defer></script><script src="../assets/module-lessons.js" defer></script></body></html>`;
}
