import {readFile,writeFile,mkdir,readdir,stat} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import path from 'node:path';
import sharp from 'sharp';
const root=path.resolve('output/UX_REVIEW_ASTRA_2026_09_05/brochures'),qa=path.join(root,'qa');await mkdir(qa,{recursive:true});
const manifest=JSON.parse(await readFile(path.join(root,'manifest.json'),'utf8')),results=[];
for(const c of manifest){const pdf=path.resolve('output/UX_REVIEW_ASTRA_2026_09_05',c.pdf),prefix=path.join(qa,c.slug);execFileSync('pdftoppm',['-scale-to','1600','-png',pdf,prefix]);const info=execFileSync('pdfinfo',[pdf],{encoding:'utf8'}),text=execFileSync('C:/Users/gajap/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe',['-c','import sys; from pypdf import PdfReader; sys.stdout.reconfigure(encoding="utf-8"); print("\\n".join(p.extract_text() or "" for p in PdfReader(sys.argv[1]).pages))',pdf],{encoding:'utf8'});const pages=Number(info.match(/Pages:\s+(\d+)/)?.[1]);const images=(await readdir(qa)).filter(f=>f.startsWith(c.slug+'-')&&f.endsWith('.png')&&!f.includes('contact')).sort();const overlays=[];for(let i=0;i<images.length;i++){const data=await sharp(path.join(qa,images[i])).resize({width:400}).png().toBuffer();overlays.push({input:data,left:(i%2)*420,top:Math.floor(i/2)*586});}await sharp({create:{width:840,height:1758,channels:3,background:'#dfe4ef'}}).composite(overlays).png().toFile(path.join(qa,c.slug+'-contact.png'));
const result={slug:c.slug,pages,a4:(()=>{const m=info.match(/Page size:\s+([\d.]+) x ([\d.]+)/);return !!m&&+m[1]>594&&+m[1]<597&&+m[2]>840&&+m[2]<844;})(),searchable:text.length>1000,bytes:(await stat(pdf)).size,titlePresent:text.replace(/\s+/g,' ').includes(c.title),textCharacters:text.length,standaloneSap:/SAP Enterprise Consulting|sap-enterprise-consulting/i.test(text),layout:c.layout};results.push(result);console.log(JSON.stringify(result));}
await writeFile(path.join(qa,'PDF_QA.json'),JSON.stringify(results,null,2));if(results.some(r=>r.pages!==6||!r.a4||!r.searchable||r.standaloneSap||r.layout.badImages.length||r.layout.overflow.length))process.exitCode=1;
