export function reviewPanel(icon, gallery=false){
 const page=n=>(gallery?'pages/':'')+String(n).padStart(3,'0')+'.html';
 const groups=[
 ['Learning formats','BookOpen',[[87,'Free C · text lesson'],[89,'Free C++ · video lesson'],[82,'Video course'],[83,'Text course'],[84,'Text + video lesson'],[91,'DSA · interactive simulation']]],
 ['Practice & learner tools','Code2',[[54,'Code editor & live preview'],[58,'Project files & downloads'],[69,'Saved notes'],[70,'Lesson discussion'],[18,'Learner dashboard'],[107,'Hybrid schedule'],[108,'Offline attendance']]],
 ['Exams & certificates','Award',[[109,'Completion checklist'],[21,'Exam instructions'],[22,'Take exam example'],[23,'Results'],[24,'Certificate example'],[110,'Retry & improvement'],[111,'Verification error state']]],
 ['Venture & investors','Rocket',[[9,'Venture program'],[10,'Submit an idea'],[153,'Idea approval queue'],[81,'Founder workspace'],[146,'Investor network'],[147,'Investor registration'],[157,'Founder introductions']]],
 ['Content & administration','ShieldCheck',[[31,'Course management'],[62,'Text content authoring'],[95,'Super Admin · publishing'],[94,'Protected setting approval'],[136,'Employee roles'],[40,'Organization dashboard'],[45,'CRM & follow-ups']]],
 ['Explore all programs','Compass',[[2,'All courses'],[3,'Learning paths'],[85,'Free courses'],[59,'Blogs & community'],[44,'Webinar example'],[158,'Individual PDF brochures'],[183,'Complete learning experience']]]
 ];
 return `<section class="client-review" aria-labelledby="client-review-title"><div class="review-heading"><div><span class="eyebrow">Client review · start here</span><h2 id="client-review-title">Explore the experiences that matter</h2><p>Direct links to the key journeys—no need to search through screenshots.</p></div><a class="button" href="${gallery?'index.html':'../index.html'}">${icon('LayoutGrid')}All 183 screens</a></div><div class="review-priority">${[[183,'Learning formats','PlayCircle'],[24,'Certificate example','Award'],[158,'All course brochures','LibraryBig']].map(([n,t,i])=>`<a href="${page(n)}">${icon(i)}<strong>${t}</strong>${icon('ArrowRight')}</a>`).join('')}<a href="${gallery?'':'../'}brochures/all-course-brochures.zip" download>${icon('Download')}<strong>Download all 12 PDFs</strong>${icon('ArrowDownToLine')}</a></div><div class="review-groups">${groups.map(([title,i,items])=>`<section><h3>${icon(i)}${title}</h3><ul>${items.map(([n,t])=>`<li><a href="${page(n)}" data-destination="${n}">${t}${icon('ChevronRight')}</a></li>`).join('')}</ul></section>`).join('')}</div><p class="review-disclaimer">${icon('Info')}Customer-review prototype: video, approvals, payments and certificates demonstrate the intended experience. Production services are not connected. Brochures download without a form.</p></section>`;
}
